// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=306f145a8ae4
import { createResourceClient } from "@flaredev/core/client";
import type companyResource from "./company.resource";

export const companyClient = createResourceClient<typeof companyResource>("/api/companies");

export type Company = typeof companyResource.$types.record;
export type CompanyCreate = typeof companyResource.$types.create;
export type CompanyUpdate = typeof companyResource.$types.update;
// generated:end
