// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start
import { createValidators } from "@flare/core";
import companyResource from "./company.resource";

export const companyValidators = createValidators(companyResource);
// generated:end
