// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b7e30340e0e2
import { createValidators } from "@flaredev/core";
import companyResource from "./company.resource";

export const companyValidators = createValidators(companyResource);
// generated:end
