// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start
import { createValidators } from "@flare/core";
import contactResource from "./contact.resource";

export const contactValidators = createValidators(contactResource);
// generated:end
