// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a9165f04ea1f
import { createResourceClient } from "@flaredev/core/client";
import type contactResource from "./contact.resource";

export const contactClient = createResourceClient<typeof contactResource>("/api/contacts");

export type Contact = typeof contactResource.$types.record;
export type ContactCreate = typeof contactResource.$types.create;
export type ContactUpdate = typeof contactResource.$types.update;
// generated:end
