// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=e4664f031dc5
import { createResourceClient } from "@flaredev/core/client";
import type customerResource from "./customer.resource";

export const customerClient = createResourceClient<typeof customerResource>("/api/customers");

export type Customer = typeof customerResource.$types.record;
export type CustomerCreate = typeof customerResource.$types.create;
export type CustomerUpdate = typeof customerResource.$types.update;
// generated:end
