// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d1461b9229bd
import { createValidators } from "@flare/core";
import customerResource from "./customer.resource";

export const customerValidators = createValidators(customerResource);
// generated:end
