// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=aea3ee8623b3
import { createResourceClient } from "@flare/core/client";
import type dealResource from "./deal.resource";

export const dealClient = createResourceClient<typeof dealResource>("/api/deals");

export type Deal = typeof dealResource.$types.record;
export type DealCreate = typeof dealResource.$types.create;
export type DealUpdate = typeof dealResource.$types.update;
// generated:end
