// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start
import { createValidators } from "@flare/core";
import dealResource from "./deal.resource";

export const dealValidators = createValidators(dealResource);
// generated:end
