// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=accd716c33b4
import { createValidators } from "@flaredev/core";
import dealResource from "./deal.resource";

export const dealValidators = createValidators(dealResource);
// generated:end
