// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=643741386d90
import { createResourceClient } from "@flare/core/client";
import type planResource from "./plan.resource";

export const planClient = createResourceClient<typeof planResource>("/api/plans");

export type Plan = typeof planResource.$types.record;
export type PlanCreate = typeof planResource.$types.create;
export type PlanUpdate = typeof planResource.$types.update;
// generated:end
