// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=514b4a94370e
import { createValidators } from "@flaredev/core";
import planResource from "./plan.resource";

export const planValidators = createValidators(planResource);
// generated:end
