// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=ef705ae8dc3b
import { createValidators } from "@flare/core";
import planResource from "./plan.resource";

export const planValidators = createValidators(planResource);
// generated:end
