// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=5d1d17dba5a1
import { createValidators } from "@flaredev/core";
import purchaseResource from "./purchase.resource";

export const purchaseValidators = createValidators(purchaseResource);
// generated:end
