// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=10626841c898
import { createResourceClient } from "@flare/core/client";
import type purchaseResource from "./purchase.resource";

export const purchaseClient = createResourceClient<typeof purchaseResource>("/api/purchases");

export type Purchase = typeof purchaseResource.$types.record;
export type PurchaseCreate = typeof purchaseResource.$types.create;
export type PurchaseUpdate = typeof purchaseResource.$types.update;
// generated:end
