// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=9737010b97dd
import { createValidators } from "@flare/core";
import purchaseResource from "./purchase.resource";

export const purchaseValidators = createValidators(purchaseResource);
// generated:end
