// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=aafb1bc98a82
import { createResourceClient } from "@flare/core/client";
import type securityEventResource from "./security-event.resource";

export const securityEventClient = createResourceClient<typeof securityEventResource>("/api/security-events");

export type SecurityEvent = typeof securityEventResource.$types.record;
export type SecurityEventCreate = typeof securityEventResource.$types.create;
export type SecurityEventUpdate = typeof securityEventResource.$types.update;
// generated:end
