// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=9d4e6ec4a27a
import { createValidators } from "@flare/core";
import securityEventResource from "./security-event.resource";

export const securityEventValidators = createValidators(securityEventResource);
// generated:end
