// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=eba68863da26
import { createResourceClient } from "@flaredev/core/client";
import type vendorResource from "./vendor.resource";

export const vendorClient = createResourceClient<typeof vendorResource>("/api/vendors");

export type Vendor = typeof vendorResource.$types.record;
export type VendorCreate = typeof vendorResource.$types.create;
export type VendorUpdate = typeof vendorResource.$types.update;
// generated:end
