// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=369ad0e8e65f
import { createValidators } from "@flaredev/core";
import vendorResource from "./vendor.resource";

export const vendorValidators = createValidators(vendorResource);
// generated:end
