// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a0acbbae7fdf
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import customerResource from "@/resources/customer.resource";

export default function NewCustomerPage() {
  return <ResourceFormPage resource={customerResource} />;
}
// generated:end
