// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=53a7b6cd8d36
import { RecordDetail } from "@/components/dashboard/record-detail";
import folderResource from "@/resources/folder.resource";

export default async function FolderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={folderResource} id={(await params).id} />;
}
// generated:end
