// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=39a06d3a4c91
import { RecordDetail } from "@/components/dashboard/record-detail";
import customerResource from "@/resources/customer.resource";

export default async function CustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={customerResource} id={(await params).id} />;
}
// generated:end
