// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3afd0e7290eb
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import purchaseResource from "@/resources/purchase.resource";

export default function NewPurchasePage() {
  return <ResourceFormPage resource={purchaseResource} />;
}
// generated:end
