// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=eef4b586ff19
import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { orders } from "./orders";
import { products } from "./products";

export const orderItems = sqliteTable(
  "order_items",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    orderId: text("order_id").references(() => orders.id, { onDelete: "restrict" }).notNull(),
    productId: text("product_id").references(() => products.id, { onDelete: "restrict" }).notNull(),
    name: text("name").notNull(),
    quantity: integer("quantity").notNull(),
    unitPrice: real("unit_price").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("order_items_order_id_idx").on(table.orderId),
    index("order_items_product_id_idx").on(table.productId),
    index("order_items_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
