// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=4a8810d054a1
import { sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { customers } from "./customers";

export const orders = sqliteTable(
  "orders",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    reference: text("reference").notNull().unique(),
    customerId: text("customer_id").references(() => customers.id, { onDelete: "set null" }),
    channel: text("channel", { enum: ["online","pos"] }).notNull(),
    status: text("status", { enum: ["pending","paid","fulfilled","refunded"] }).notNull(),
    total: real("total").notNull(),
    paidWith: text("paid_with", { enum: ["cash","card","mobile"] }),
    note: text("note"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("orders_customer_id_idx").on(table.customerId),
    check("orders_channel_check", sql`${table.channel} in ('online', 'pos')`),
    index("orders_channel_idx").on(table.channel),
    check("orders_status_check", sql`${table.status} in ('pending', 'paid', 'fulfilled', 'refunded')`),
    index("orders_status_idx").on(table.status),
    check("orders_paid_with_check", sql`${table.paidWith} in ('cash', 'card', 'mobile')`),
    index("orders_paid_with_idx").on(table.paidWith),
    index("orders_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
