// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=33c6c7cf337c
import { sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { categories } from "./categories";

export const products = sqliteTable(
  "products",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    sku: text("sku").notNull().unique(),
    kind: text("kind", { enum: ["stock","digital"] }).notNull(),
    price: real("price").notNull(),
    stock: integer("stock"),
    description: text("description"),
    image: text("image"),
    downloadFile: text("download_file"),
    categoryId: text("category_id").references(() => categories.id, { onDelete: "set null" }),
    active: integer("active", { mode: "boolean" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check("products_kind_check", sql`${table.kind} in ('stock', 'digital')`),
    index("products_kind_idx").on(table.kind),
    index("products_category_id_idx").on(table.categoryId),
    index("products_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
