// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=196d65b72eaa
import { RecordDetail } from "@/components/dashboard/record-detail";
import contactResource from "@/resources/contact.resource";

export default async function ContactDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={contactResource} id={(await params).id} />;
}
// generated:end
