// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b01fe170b3f6
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import purchaseResource from "@/resources/purchase.resource";

export default async function PurchaseListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">{purchaseResource.pluralLabel}</h1>
      <ResourceTable resource={purchaseResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
