import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import pc from "picocolors";
import {
  renderApiKeyActions,
  renderApiKeyControls,
  renderApiKeyModel,
  renderApiKeyPage,
  renderApiKeyTable,
} from "../generator/apikeys.js";
import { splitMarkers, writeGenerated } from "../generator/markers.js";
import { generateSchemaMigration } from "../generator/migrations.js";
import { renderNavBlock } from "../generator/nav.js";
import type { FileResult } from "../generator/plan.js";
import { API_KEY_PACKAGE, BETTER_AUTH_VERSION } from "../versions.js";
import { findAppRoot } from "./run.js";
import { readStack, type Stack } from "../stack.js";

export interface GenApiKeysOptions {
  cwd?: string;
  force?: boolean;
  /** Write the files without touching package.json or running a migration (for tests). */
  skipInstall?: boolean;
  skipMigration?: boolean;
  log?: (message: string) => void;
}

/** A header so it is obvious these files came from a generator. */
const header = () => `// Generated by \`flare gen apikeys\`. Code inside the generated block is rewritten if
// you run it again; add your own code outside it.`;

/** Add `@better-auth/api-key`, and raise better-auth to the version it peer-depends on. */
function addDependencies(appRoot: string, log: (message: string) => void): boolean {
  const path = join(appRoot, "package.json");
  const pkg = JSON.parse(readFileSync(path, "utf8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const deps = (pkg.dependencies ??= {});
  let changed = false;

  if (deps[API_KEY_PACKAGE] !== BETTER_AUTH_VERSION) {
    deps[API_KEY_PACKAGE] = BETTER_AUTH_VERSION;
    changed = true;
  }
  // The plugin peer-depends on ^1.7.7, and an app created before this existed is on an
  // earlier patch. Raising it here rather than letting the install warn about a peer.
  if (deps["better-auth"] && deps["better-auth"] !== BETTER_AUTH_VERSION) {
    log(pc.dim(`         better-auth ${deps["better-auth"]} -> ${BETTER_AUTH_VERSION} (the key plugin needs it)`));
    deps["better-auth"] = BETTER_AUTH_VERSION;
    changed = true;
  }

  if (changed) {
    // Sorted, so the diff of adding one dependency is one line.
    pkg.dependencies = Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));
    writeFileSync(path, `${JSON.stringify(pkg, null, 2)}\n`);
    log(`${pc.yellow("update".padEnd(9))} package.json (${API_KEY_PACKAGE})`);
  }
  return changed;
}

/**
 * Put `apiKey()` in the plugins array of lib/auth.ts.
 *
 * `nextCookies()` has to stay last — it is what lets a server action set a cookie — so
 * the new plugin goes immediately before it rather than at the end.
 */
function addAuthPlugin(appRoot: string, log: (message: string) => void): boolean {
  const path = join(appRoot, "lib/auth.ts");
  if (!existsSync(path)) {
    log(pc.yellow(`lib/auth.ts not found: add \`apiKey()\` to your betterAuth plugins yourself.`));
    return false;
  }
  let source = readFileSync(path, "utf8");
  if (/\bapiKey\(/.test(source)) {
    log(`${pc.dim("kept".padEnd(9))} lib/auth.ts (apiKey() already there)`);
    return false;
  }

  const importLine = `import { apiKey } from "${API_KEY_PACKAGE}";\n`;
  const anchorImport = /^import \{ admin \} from "better-auth\/plugins\/admin";$/m;
  if (anchorImport.test(source)) source = source.replace(anchorImport, (line) => importLine + line);
  else source = source.replace(/^(import .*\n)/, (line) => line + importLine);

  // Rate limiting is on by default in the plugin (10 requests a day), which is too tight
  // for the cron job this exists for; a key is a server-side credential, not a public
  // endpoint, so the window is set to something a sync job can live with.
  //
  // enableSessionForAPIKeys is deliberately left off: it mocks a session for any request
  // carrying a valid key, and the plugin's own docs advise against it in production.
  // lib/api-keys.ts verifies the key explicitly instead.
  const plugin = `    apiKey({ rateLimit: { enabled: true, timeWindow: 60_000, maxRequests: 600 } }),\n`;
  const anchorPlugin = /^(\s*)\/\/ Must stay last: lets server actions set auth cookies\.$/m;
  if (anchorPlugin.test(source)) {
    source = source.replace(anchorPlugin, (line) => plugin + line);
  } else if (/^\s*nextCookies\(\),$/m.test(source)) {
    source = source.replace(/^(\s*nextCookies\(\),)$/m, (line) => plugin + line);
  } else {
    log(pc.yellow(`Could not find the plugins array in lib/auth.ts: add \`apiKey()\` to it yourself (before nextCookies()).`));
    return false;
  }

  writeFileSync(path, source);
  log(`${pc.yellow("update".padEnd(9))} lib/auth.ts (apiKey plugin)`);
  return true;
}

/**
 * Add the plugin's table to the auth schema.
 *
 * Appended rather than regenerated. `npx @better-auth/cli generate` is the source of
 * truth for this table and would rewrite the whole file, reformatting every table in it;
 * re-run it yourself if a future version of the plugin changes its columns.
 */
function addTable(appRoot: string, stack: Stack, log: (message: string) => void): boolean {
  const relative = stack === "next" ? "prisma/schema/base.prisma" : "db/auth-schema.ts";
  const path = join(appRoot, relative);
  if (!existsSync(path)) {
    log(pc.yellow(`${relative} not found: add the apikey table yourself (\`npx @better-auth/cli generate\`).`));
    return false;
  }
  const source = readFileSync(path, "utf8");
  if (stack === "next" ? /model ApiKey\b/.test(source) : /sqliteTable\(\s*\n?\s*"apikey"/.test(source)) {
    log(`${pc.dim("kept".padEnd(9))} ${relative} (the apikey table is already there)`);
    return false;
  }
  const addition = stack === "next" ? renderApiKeyModel() : renderApiKeyTable();
  writeFileSync(path, `${source.replace(/\s*$/, "")}\n${addition}`);
  log(`${pc.yellow("update".padEnd(9))} ${relative} (apikey table)`);
  return true;
}

/**
 * `flare gen apikeys`
 *
 * Switches on API keys for clients that cannot hold a cookie — a cron job, a script, a
 * mobile app, a partner integration.
 *
 * Better Auth's `@better-auth/api-key` owns the table, the minting, the hashing, expiry,
 * revocation and the per-key rate limit. This adds the part it leaves to the app: turning
 * a verified key into the user whose role and records a policy is checked against
 * (`lib/api-keys.ts`, which every app already calls from `lib/api.ts`), and a screen to
 * manage them.
 */
export async function genApiKeys(options: GenApiKeysOptions = {}): Promise<{ files: FileResult[]; migrations: string[] }> {
  const log = options.log ?? ((message: string) => console.log(message));
  const appRoot = findAppRoot(options.cwd ?? process.cwd());
  const stack = readStack(appRoot);

  const files: FileResult[] = [];
  const write = (path: string, content: string) => {
    const absolute = join(appRoot, path);
    mkdirSync(dirname(absolute), { recursive: true });
    const outcome = writeGenerated(absolute, content, { header: header(), force: options.force });
    files.push({ path, status: "missing", outcome });
    const label = outcome === "create" ? pc.green("create") : outcome === "update" ? pc.yellow("update") : pc.dim("identical");
    log(`${label.padEnd(18)} ${path}`);
  };

  write("app/dashboard/api-keys/actions.ts", renderApiKeyActions());
  write("app/dashboard/api-keys/page.tsx", renderApiKeyPage());
  write("app/dashboard/api-keys/key-controls.tsx", renderApiKeyControls());

  if (!existsSync(join(appRoot, "lib/api-keys.ts"))) {
    log(pc.yellow(`lib/api-keys.ts not found — this app predates API key support. Run \`flare update lib/api-keys.ts\` and \`flare update lib/api.ts\`.`));
  }

  addAuthPlugin(appRoot, log);
  const tableAdded = addTable(appRoot, stack, log);

  const navPath = join(appRoot, "lib/dashboard-nav.ts");
  if (existsSync(navPath) && splitMarkers(readFileSync(navPath, "utf8"))) {
    write("lib/dashboard-nav.ts", renderNavBlock(readFileSync(navPath, "utf8"), [{ label: "API keys", href: "/dashboard/api-keys", icon: "key-round" }]));
  } else {
    log(pc.yellow(`lib/dashboard-nav.ts not found: link to /dashboard/api-keys from your sidebar yourself.`));
  }

  const installed = options.skipInstall ? false : addDependencies(appRoot, log);

  // Drizzle can diff the schema into a migration; Prisma writes its own, and doing it
  // here would mean running `prisma migrate dev` against whatever DATABASE_URL happens
  // to be set, which is not a thing a generator should decide.
  let migrations: string[] = [];
  if (stack !== "next" && tableAdded && !options.skipMigration) {
    const result = await generateSchemaMigration(appRoot, "apikeys");
    migrations = result.files;
    for (const file of migrations) log(`${pc.green("create".padEnd(9))} ${file}`);
    for (const repair of result.repairs) log(pc.dim(`repaired  ${repair}`));
  }

  const steps = [
    ...(installed ? [`${pc.bold("install")} (pnpm install) to fetch ${API_KEY_PACKAGE}.`] : []),
    stack === "next"
      ? `${pc.bold("npx prisma migrate dev --name apikeys")} to create the table.`
      : `${pc.bold("flare migrate")} to create the apikey table.`,
    `${pc.bold("flare dev")}, then ${pc.bold("/dashboard/api-keys")} to mint one.`,
    `Call the API with it: ${pc.bold("-H 'Authorization: Bearer <key>'")} (or ${pc.bold("x-api-key")}).`,
  ];
  log(["", "Next:", ...steps.map((step, index) => `  ${index + 1}. ${step}`), ""].join("\n"));
  log(
    pc.dim(
      "A key acts as the user who created it: same role, and with a policy that has `own`, the same rows. It is not a\nway past a policy, which is why there is nothing to configure per key.",
    ),
  );
  return { files, migrations };
}
