import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import pc from "picocolors";
import { descriptorPath, renderDescriptor, resourceName } from "../generator/descriptor.js";
import { parseFields } from "../generator/grammar.js";
import { loadResources, type LoadedResource } from "../generator/load.js";
import { writeGenerated, type WriteOutcome } from "../generator/markers.js";
import { generateSchemaMigration } from "../generator/migrations.js";
import { renderRegistry, renderSchemaIndex, resourceFiles } from "../generator/render.js";
import { templatesDir } from "../utils/fs.js";
import { findAppRoot } from "./run.js";

export interface GenResourceOptions {
  fields?: string;
  cwd?: string;
  /** Skip running drizzle-kit (tests without an installed app). */
  skipMigration?: boolean;
  log?: (message: string) => void;
}

export interface GenResult {
  name: string;
  written: { path: string; outcome: WriteOutcome }[];
  migrations: string[];
}

const HEADER = (name: string) =>
  `// Generated by \`flare gen resource ${name}\`. Code inside the generated block is\n` +
  `// rewritten on regeneration; add your own code outside it.\n`;

/** Files every app needs once resources exist (copied from the app template if missing). */
function ensureSupportFiles(appRoot: string, log: (message: string) => void) {
  const apiHelper = join(appRoot, "lib/api.ts");
  if (!existsSync(apiHelper)) {
    mkdirSync(dirname(apiHelper), { recursive: true });
    copyFileSync(join(templatesDir, "app/lib/api.ts"), apiHelper);
    log(`${pc.green("create")} lib/api.ts`);
  }
}

/** Write every derived file for `targets`, plus the shared registry and schema index. */
export function writeResourceFiles(
  appRoot: string,
  all: LoadedResource[],
  targets: LoadedResource[],
  log: (message: string) => void,
): GenResult["written"] {
  const written: GenResult["written"] = [];
  const write = (path: string, content: string, header?: string) => {
    const outcome = writeGenerated(join(appRoot, path), content, { header });
    written.push({ path, outcome });
    const color = outcome === "create" ? pc.green : outcome === "update" ? pc.yellow : pc.dim;
    log(`${color(outcome.padEnd(9))} ${path}`);
  };

  for (const entry of targets) {
    for (const file of resourceFiles(entry, all)) write(file.path, file.content, HEADER(entry.resource.name));
  }
  write("resources/index.ts", renderRegistry(all), "// Registry of every resource descriptor (maintained by flare gen).\n");
  write("db/schema.ts", renderSchemaIndex(all));
  return written;
}

export async function genResource(rawName: string, options: GenResourceOptions): Promise<GenResult> {
  const log = options.log ?? ((message: string) => console.log(message));
  const appRoot = findAppRoot(options.cwd ?? process.cwd());
  const name = resourceName(rawName);
  if (!options.fields) throw new Error(`--fields is required, e.g. flare gen resource ${name} --fields "name:string, email:string"`);

  const fields = parseFields(options.fields);
  const relativePath = descriptorPath(name);
  const path = join(appRoot, relativePath);
  if (existsSync(path)) throw new Error(`${relativePath} already exists.`);

  // Validate relation targets before writing anything.
  const existing = await loadResources(appRoot);
  const known = new Set([name, ...existing.map(({ resource }) => resource.name)]);
  for (const field of fields) {
    if (field.kind === "belongsTo" && !known.has(field.target!)) {
      throw new Error(`${name}.${field.key} belongs to "${field.target}", which doesn't exist yet. Generate ${field.target} first.`);
    }
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderDescriptor(name, fields));
  log(`${pc.green("create".padEnd(9))} ${relativePath}`);

  let written: GenResult["written"];
  let table: string;
  try {
    const all = await loadResources(appRoot);
    const target = all.find(({ resource }) => resource.name === name)!;
    table = target.resource.table;
    ensureSupportFiles(appRoot, log);
    written = writeResourceFiles(appRoot, all, [target], log);
  } catch (error) {
    throw new Error(`${error instanceof Error ? error.message : String(error)}\n(${relativePath} was written; fix it and run \`flare sync-types\`.)`);
  }

  let migrations: string[] = [];
  if (!options.skipMigration) {
    const result = await generateSchemaMigration(appRoot, `create_${table}`);
    migrations = result.files;
    for (const file of migrations) log(`${pc.green("create".padEnd(9))} ${file}`);
    if (migrations.length) log(`\nNext: ${pc.bold("flare migrate")} to apply it locally.`);
  }

  return { name, written: [{ path: relativePath, outcome: "create" }, ...written], migrations };
}
