// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d7127141cc48
import { RecordDetail } from "@/components/dashboard/record-detail";
import companyResource from "@/resources/company.resource";

export default async function CompanyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={companyResource} id={(await params).id} />;
}
// generated:end
