// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=19097d48580e
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import productResource from "@/resources/product.resource";

export default async function EditProductPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={productResource} id={(await params).id} />;
}
// generated:end
