// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=8a9dc681cfb1
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import fileResource from "@/resources/file.resource";

export const metadata = { title: fileResource.pluralLabel };

export default async function FileListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={fileResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: fileResource.pluralLabel }]}
      />
      <ResourceStats resource={fileResource} />
      <ResourceChart resource={fileResource} />
      <ResourceTable resource={fileResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
