// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=fc0579e6edc3
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import orderResource from "@/resources/order.resource";

export default function NewOrderPage() {
  return <ResourceFormPage resource={orderResource} />;
}
// generated:end
