// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b0e5c6dc08bb
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { categories } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import categoryResource from "@/resources/category.resource";

const handlers = createResourceHandlers({
  resource: categoryResource,
  table: categories,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
