// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=97eba16b295f
import { RecordDetail } from "@/components/dashboard/record-detail";
import orderResource from "@/resources/order.resource";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={orderResource} id={(await params).id} />;
}
// generated:end
