// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=0143159243ac
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import contactResource from "@/resources/contact.resource";

export const metadata = { title: contactResource.pluralLabel };

export default async function ContactListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={contactResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: contactResource.pluralLabel }]}
      />
      <ResourceStats resource={contactResource} />
      <ResourceChart resource={contactResource} />
      <ResourceTable resource={contactResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
