// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=ecf477499629
import { RecordDetail } from "@/components/dashboard/record-detail";
import productResource from "@/resources/product.resource";

export default async function ProductDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={productResource} id={(await params).id} />;
}
// generated:end
