// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=0b4c457eb918
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import folderResource from "@/resources/folder.resource";

export default async function EditFolderPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={folderResource} id={(await params).id} />;
}
// generated:end
