packages:
  - packages/*
  - examples/*
  - docs

allowBuilds:
  esbuild: true
  workerd: true
  sharp: false
  '@prisma/engines': true
  prisma: true

minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.42.2'
