// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c3a3e655b9aa
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { files } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import fileResource from "@/resources/file.resource";

const handlers = createResourceHandlers({
  resource: fileResource,
  table: files,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
