// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=022a708b46f6
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import categoryResource from "@/resources/category.resource";

export const metadata = { title: categoryResource.pluralLabel };

export default async function CategoryListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={categoryResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: categoryResource.pluralLabel }]}
      />
      <ResourceStats resource={categoryResource} />
      <ResourceChart resource={categoryResource} />
      <ResourceTable resource={categoryResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
