// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=53eaf90bf6c1
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import securityEventResource from "@/resources/security-event.resource";

export const metadata = { title: securityEventResource.pluralLabel };

export default async function SecurityEventListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={securityEventResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: securityEventResource.pluralLabel }]}
      />
      <ResourceStats resource={securityEventResource} />
      <ResourceTable resource={securityEventResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
