// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=57eaf4ce849a
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import planResource from "@/resources/plan.resource";

export default function NewPlanPage() {
  return <ResourceFormPage resource={planResource} />;
}
// generated:end
