// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=31ccc40a7c0a
import { ResourceListSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return <ResourceListSkeleton columns={2} />;
}
// generated:end
