// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=58a575f27481
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import companyResource from "@/resources/company.resource";

export const metadata = { title: companyResource.pluralLabel };

export default async function CompanyListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={companyResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: companyResource.pluralLabel }]}
      />
      <ResourceStats resource={companyResource} />
      <ResourceChart resource={companyResource} />
      <ResourceTable resource={companyResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
