// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=8f6607fda23a
import { createResourceHandlers } from "@flare/core/server";
import { getDb } from "@/db";
import { companies } from "@/db/schema";
import { authorize } from "@/lib/api";
import companyResource from "@/resources/company.resource";

const handlers = createResourceHandlers({
  resource: companyResource,
  table: companies,
  getDb,
  authorize,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
