// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=9c7184849183
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { companies } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import companyResource from "@/resources/company.resource";

const handlers = createResourceHandlers({
  resource: companyResource,
  table: companies,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
