// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=03272fd533a7
import { createResourceHandlers, drizzleRows } from "@/lib/resource";
import { getDb } from "@/db";
import { companies } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import companyResource from "@/resources/company.resource";

const handlers = createResourceHandlers({
  resource: companyResource,
  rows: drizzleRows(companies, getDb),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
