// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=20f104279751
import { createResourceStore, prismaRows, crossOrigin, drain, failureResponse, problem, readJson, respond } from "@/lib/resource";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import productResource from "@/resources/product.resource";

const store = createResourceStore({
  resource: productResource,
  rows: prismaRows(prisma.product, prisma),
  currentUser,
  onChange: revalidateResource,
});

/** GET /api/products — list products. Query: page, perPage, sort, q, filter[field], cursor. */
export async function GET(request: Request): Promise<Response> {
  const denied = await authorize({ request, resource: productResource, action: "list" });
  if (denied) return denied;

  return respond(await store.list(new URL(request.url).searchParams));
}

/** POST /api/products — create one. */
export async function POST(request: Request): Promise<Response> {
  try {
    const denied = await authorize({ request, resource: productResource, action: "create" });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    const result = await store.create(read.body);
    if (!result.ok) return failureResponse(result);

    const location = `${new URL(request.url).pathname.replace(/\/$/, "")}/${result.data.id as string}`;
    return Response.json(result.data, { status: 201, headers: { location } });
  } finally {
    // A body left unread breaks the next request through wrangler's dev proxy.
    await drain(request);
  }
}
// generated:end
