// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3a7842cd049a
import { createResourceHandlers } from "@flaredev/core/server";
import { prismaRows } from "@flaredev/core/server";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import productResource from "@/resources/product.resource";

const handlers = createResourceHandlers({
  resource: productResource,
  rows: prismaRows(prisma.product, prisma),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
