// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b6b4f32d9ddb
import { RecordDetail } from "@/components/dashboard/record-detail";
import orderItemResource from "@/resources/order-item.resource";

export default async function OrderItemDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={orderItemResource} id={(await params).id} />;
}
// generated:end
