// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=19960a70fcb6
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import contactResource from "@/resources/contact.resource";

export default function NewContactPage() {
  return <ResourceFormPage resource={contactResource} />;
}
// generated:end
