// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=6dbbbb8a13ff
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import vendorResource from "@/resources/vendor.resource";

export const metadata = { title: vendorResource.pluralLabel };

export default async function VendorListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={vendorResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: vendorResource.pluralLabel }]}
      />
      <ResourceStats resource={vendorResource} />
      <ResourceTable resource={vendorResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
