// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a9fc93d7ff83
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { files } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import fileResource from "@/resources/file.resource";

const handlers = createResourceHandlers({
  resource: fileResource,
  table: files,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
