// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=14c97e33ebbe
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import dealResource from "@/resources/deal.resource";

export default async function EditDealPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={dealResource} id={(await params).id} />;
}
// generated:end
