// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=53d7c86c6308
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { customers } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import customerResource from "@/resources/customer.resource";

const handlers = createResourceHandlers({
  resource: customerResource,
  table: customers,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
