// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=65520bd09260
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import vendorResource from "@/resources/vendor.resource";

export default async function EditVendorPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={vendorResource} id={(await params).id} />;
}
// generated:end
