// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3b01812a7859
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import orderItemResource from "@/resources/order-item.resource";

export const metadata = { title: orderItemResource.pluralLabel };

export default async function OrderItemListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={orderItemResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: orderItemResource.pluralLabel }]}
      />
      <ResourceStats resource={orderItemResource} />
      <ResourceChart resource={orderItemResource} />
      <ResourceTable resource={orderItemResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
