// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=542f1816841a
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { purchases } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import purchaseResource from "@/resources/purchase.resource";

const handlers = createResourceHandlers({
  resource: purchaseResource,
  table: purchases,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
