// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=69f9f8027665
import { createResourceHandlers } from "@flaredev/core/server";
import { prismaRows } from "@flaredev/core/server";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import orderResource from "@/resources/order.resource";

const handlers = createResourceHandlers({
  resource: orderResource,
  rows: prismaRows(prisma.order, prisma),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
