// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=bdede4643129
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import purchaseResource from "@/resources/purchase.resource";

export default async function EditPurchasePage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={purchaseResource} id={(await params).id} />;
}
// generated:end
