// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=610c28dfb31f
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import contactResource from "@/resources/contact.resource";

export default function NewContactPage() {
  return <ResourceFormPage resource={contactResource} />;
}
// generated:end
