// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=9b3152c5b17b
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import orderItemResource from "@/resources/order-item.resource";

export default function NewOrderItemPage() {
  return <ResourceFormPage resource={orderItemResource} />;
}
// generated:end
