// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1ec50f8d8763
import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { folders } from "./folders";

export const files = sqliteTable(
  "files",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    folderId: text("folder_id").references(() => folders.id, { onDelete: "set null" }),
    content: text("content").notNull(),
    size: integer("size").notNull(),
    contentType: text("content_type"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("files_folder_id_idx").on(table.folderId),
    index("files_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
