// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=aaad47820b74
import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";

export const folders = sqliteTable(
  "folders",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    parentId: text("parent_id").references((): AnySQLiteColumn => folders.id, { onDelete: "set null" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("folders_parent_id_idx").on(table.parentId),
    index("folders_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
