// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3f0cb5493dc0
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { categories } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import categoryResource from "@/resources/category.resource";

const handlers = createResourceHandlers({
  resource: categoryResource,
  table: categories,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
