import { parseFields } from "./grammar.js";
import { renderDescriptor, renderField } from "./descriptor.js";
import type { ParsedField } from "./grammar.js";

/**
 * `flare gen billing` scaffolding (Stripe).
 *
 * Three regular Flare resources carry the data:
 *
 *   Plan     – one row per Stripe Price. Recurring prices are subscription plans;
 *              one-time prices are things to buy once. `flare billing:sync-plans`
 *              mirrors them from Stripe.
 *   Customer – who pays. A signed-in user checks out, and the webhook keeps this
 *              row's subscription state in sync ("Subscription fields on Customer").
 *   Purchase – one row per paid one-time Checkout.
 *
 * The rules that decide subscription state live in `@flare/core` (billing.ts) and
 * are unit-tested there; the files generated here are the Stripe and database glue.
 */

export const BILLING_PROVIDER = "stripe" as const;
export const BILLING_MODES = ["subscriptions"] as const;

export function validateBillingOptions(provider: string | undefined, mode: string | undefined) {
  if (provider && provider !== BILLING_PROVIDER) {
    throw new Error(`--provider "${provider}" is not supported yet. Supported: ${BILLING_PROVIDER}.`);
  }
  if (mode && !(BILLING_MODES as readonly string[]).includes(mode)) {
    throw new Error(`--mode "${mode}" is not supported. Supported: ${BILLING_MODES.join(", ")} (it includes one-time checkout too).`);
  }
}

/** Plan: one row per Stripe Price. `interval` is empty for one-time prices. */
export const PLAN_FIELDS =
  "name:string, slug:string!, description:text?, stripeProductId:string?, stripePriceId:string!, " +
  "amount:int, currency:string, interval:enum(month,year)?, active:boolean?, sort:int?";

/** The subscription fields every Customer needs, merged into an existing Customer too. */
export const CUSTOMER_FIELDS =
  "name:string, email:string!, userId:string!?, stripeCustomerId:string!?, stripeSubscriptionId:string?, " +
  "subscriptionStatus:enum(none,incomplete,trialing,active,past_due,paused,canceled,unpaid)?, " +
  "subscriptionEndsAt:datetime?, cancelAtPeriodEnd:boolean?, planId:belongsTo(Plan)?";

/** Purchase: one row per one-time Checkout, keyed by its session so webhooks are idempotent. */
export const PURCHASE_FIELDS =
  "customerId:belongsTo(Customer), planId:belongsTo(Plan)?, stripeCheckoutSessionId:string!, " +
  "amount:int, currency:string, status:enum(pending,paid,failed)";

export const BILLING_RESOURCES = {
  Plan: PLAN_FIELDS,
  Customer: CUSTOMER_FIELDS,
  Purchase: PURCHASE_FIELDS,
} as const;
export type BillingResource = keyof typeof BILLING_RESOURCES;

export const billingFields = (name: BillingResource): ParsedField[] => parseFields(BILLING_RESOURCES[name]);

export const renderBillingDescriptor = (name: BillingResource): string => renderDescriptor(name, billingFields(name));

/**
 * Add the billing fields an existing descriptor's tracked block is missing, keeping
 * every field it already has. Returns null when nothing is missing.
 */
export function mergeBillingFields(name: BillingResource, block: string): string | null {
  const present = new Set([...block.matchAll(/^\s*(\w+)\s*:/gm)].map((match) => match[1]));
  const missing = billingFields(name).filter((field) => !present.has(field.key));
  if (missing.length === 0) return null;
  const lines = missing.map((field) => `${renderField(field)}\n`).join("");
  return `${block.replace(/\s*$/, "\n")}${lines}`;
}

/**
 * Who may use the billing records through the admin and the REST API. Customers
 * hold other people's email and Stripe ids and their subscription status is what
 * grants access, so only the webhook (server code, not the API) may write them.
 */
export const BILLING_POLICIES: Record<BillingResource, { read: string[]; create: string[]; update: string[]; delete: string[] }> = {
  Plan: { read: ["*"], create: ["admin"], update: ["admin"], delete: ["admin"] },
  Customer: { read: ["admin", "staff"], create: ["admin"], update: ["admin"], delete: ["admin"] },
  Purchase: { read: ["admin", "staff"], create: ["admin"], update: ["admin"], delete: ["admin"] },
};

export const billingHeader = () =>
  `// Generated by \`flare gen billing\`. Code inside the generated block is\n` +
  `// rewritten on regeneration; add your own code outside it.\n`;

const STRIPE_API_VERSION = "2026-08-26.dahlia";

/** `lib/stripe.ts`: the Stripe client, customer linking, and the webhook's database sync. */
export const renderLibStripe = (): string => `import Stripe from "stripe";
import { env } from "cloudflare:workers";
import { and, eq, isNull } from "drizzle-orm";
import { checkoutPaid, shouldApplySubscription, subscriptionState } from "@flare/core";
import { getDb } from "@/db";
import { customers, plans, purchases } from "@/db/schema";

export type CustomerRow = typeof customers.$inferSelect;

export function stripeSecrets(): { STRIPE_SECRET_KEY?: string; STRIPE_WEBHOOK_SECRET?: string; BETTER_AUTH_URL?: string } {
  return env as { STRIPE_SECRET_KEY?: string; STRIPE_WEBHOOK_SECRET?: string; BETTER_AUTH_URL?: string };
}

/** The Stripe client. Throws a clear error when STRIPE_SECRET_KEY is unset. */
export function createStripe(): Stripe {
  const { STRIPE_SECRET_KEY } = stripeSecrets();
  if (!STRIPE_SECRET_KEY) {
    throw new Error("STRIPE_SECRET_KEY is not set. Add it to .dev.vars locally and run \`wrangler secret put STRIPE_SECRET_KEY\` for production.");
  }
  return new Stripe(STRIPE_SECRET_KEY, { apiVersion: "${STRIPE_API_VERSION}", httpClient: Stripe.createFetchHttpClient() });
}

/**
 * The app's own origin for Checkout and portal return URLs. Comes from
 * BETTER_AUTH_URL when set, else the request URL, never from forwarded headers
 * a client could spoof to send users elsewhere after paying.
 */
export function appOrigin(request: Request): string {
  const configured = stripeSecrets().BETTER_AUTH_URL;
  return (configured ? new URL(configured) : new URL(request.url)).origin;
}

/**
 * The Customer row that pays for a signed-in user, with a Stripe customer attached.
 * Creates both on first use, links a row an admin created for the same email, and
 * backfills a row that has no Stripe customer yet. The idempotency key makes a
 * double click create one Stripe customer, not two.
 */
export async function getOrCreateCustomer(user: { id: string; email: string; name: string | null }): Promise<CustomerRow & { stripeCustomerId: string }> {
  const db = getDb();
  let row: CustomerRow | undefined =
    (await db.select().from(customers).where(eq(customers.userId, user.id)).get()) ??
    (await db
      .update(customers)
      .set({ userId: user.id })
      .where(and(eq(customers.email, user.email), isNull(customers.userId)))
      .returning()
      .get());
  if (!row) {
    row = await db
      .insert(customers)
      .values({ id: crypto.randomUUID(), name: user.name ?? user.email, email: user.email, userId: user.id, subscriptionStatus: "none", createdAt: new Date(), updatedAt: new Date() })
      .onConflictDoNothing()
      .returning()
      .get();
    row ??= await db.select().from(customers).where(eq(customers.userId, user.id)).get();
    if (!row) throw new Error("Could not create the customer record.");
  }
  if (row.stripeCustomerId) return row as CustomerRow & { stripeCustomerId: string };

  const stripeCustomer = await createStripe().customers.create(
    { email: user.email, name: user.name ?? undefined, metadata: { flareCustomerId: row.id } },
    { idempotencyKey: \`flare-customer-\${row.id}\` },
  );
  const linked = await db.update(customers).set({ stripeCustomerId: stripeCustomer.id, updatedAt: new Date() }).where(eq(customers.id, row.id)).returning().get();
  return linked as CustomerRow & { stripeCustomerId: string };
}

let portalConfiguration: string | undefined;

/**
 * The portal configuration \`flare billing:sync-plans\` maintains (tagged flare=billing),
 * which allows switching between the synced plans. Undefined falls back to the
 * account's default portal settings.
 */
export async function billingPortalConfiguration(stripe: Stripe): Promise<string | undefined> {
  if (portalConfiguration) return portalConfiguration;
  for await (const configuration of stripe.billingPortal.configurations.list({ active: true, limit: 100 })) {
    if (configuration.metadata?.flare === "billing") return (portalConfiguration = configuration.id);
  }
  return undefined;
}

function idOf(value: string | { id: string } | null | undefined): string | null {
  if (!value) return null;
  return typeof value === "string" ? value : value.id;
}

/**
 * Write a subscription's CURRENT state to its Customer. Every event re-fetches the
 * subscription from Stripe instead of trusting the event payload, so duplicate and
 * out-of-order deliveries all converge on the same, latest state.
 */
export async function syncSubscription(subscriptionId: string): Promise<void> {
  const subscription = await createStripe().subscriptions.retrieve(subscriptionId);
  const db = getDb();
  const customer = await db.select().from(customers).where(eq(customers.stripeCustomerId, idOf(subscription.customer) ?? "")).get();
  if (!customer) return;
  if (!shouldApplySubscription(customer, subscription)) return;

  const state = subscriptionState(subscription);
  const plan = state.priceId ? await db.select({ id: plans.id }).from(plans).where(eq(plans.stripePriceId, state.priceId)).get() : undefined;
  await db
    .update(customers)
    .set({
      stripeSubscriptionId: state.stripeSubscriptionId,
      subscriptionStatus: state.subscriptionStatus,
      // datetime fields are stored as ISO text.
      subscriptionEndsAt: state.subscriptionEndsAt?.toISOString() ?? null,
      cancelAtPeriodEnd: state.cancelAtPeriodEnd,
      planId: plan?.id ?? null,
      updatedAt: new Date(),
    })
    .where(eq(customers.id, customer.id));
}

/**
 * A Checkout Session finished. Subscriptions sync from Stripe; one-time payments
 * record a Purchase, marked paid only once the money has settled.
 */
export async function syncCheckoutSession(sessionId: string): Promise<void> {
  const session = await createStripe().checkout.sessions.retrieve(sessionId, { expand: ["line_items"] });
  if (session.mode === "subscription") {
    const subscriptionId = idOf(session.subscription);
    if (subscriptionId) await syncSubscription(subscriptionId);
    return;
  }
  if (session.mode !== "payment") return;

  const db = getDb();
  const customer = await db.select().from(customers).where(eq(customers.stripeCustomerId, idOf(session.customer) ?? "")).get();
  if (!customer) return;
  const priceId = session.line_items?.data?.[0]?.price?.id ?? null;
  const plan = priceId ? await db.select({ id: plans.id }).from(plans).where(eq(plans.stripePriceId, priceId)).get() : undefined;
  const status = checkoutPaid(session) ? "paid" : session.status === "expired" ? "failed" : "pending";
  await db
    .insert(purchases)
    .values({
      id: crypto.randomUUID(),
      customerId: customer.id,
      planId: plan?.id ?? null,
      stripeCheckoutSessionId: session.id,
      amount: session.amount_total ?? 0,
      currency: session.currency ?? "usd",
      status,
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({ target: purchases.stripeCheckoutSessionId, set: { status, updatedAt: new Date() } });
}

/** A delayed one-time payment failed after the session completed. */
export async function failCheckoutSession(sessionId: string): Promise<void> {
  await getDb().update(purchases).set({ status: "failed", updatedAt: new Date() }).where(eq(purchases.stripeCheckoutSessionId, sessionId));
}

/** The subscription an invoice belongs to (its location moved in API 2025-03-31). */
export function invoiceSubscriptionId(invoice: Stripe.Invoice): string | null {
  const legacy = (invoice as unknown as { subscription?: string | { id: string } | null }).subscription;
  return idOf(invoice.parent?.subscription_details?.subscription ?? legacy ?? null);
}
`;

/** `lib/billing.ts`: read helpers for the billing page. */
export const renderLibBilling = (): string => `import { asc, desc, eq } from "drizzle-orm";
import { grantsAccess, isLiveSubscription, type SubscriptionStatus } from "@flare/core";
import { getDb } from "@/db";
import { customers, plans, purchases } from "@/db/schema";

export interface BillingSnapshot {
  status: SubscriptionStatus;
  /** Has a subscription that must be changed through the portal, not bought again. */
  live: boolean;
  /** Paid features should be on. */
  access: boolean;
  planId: string | null;
  endsAt: Date | null;
  cancelAtPeriodEnd: boolean;
}

/** The subscription state of a user's Customer row. */
export async function billingSnapshot(userId: string): Promise<BillingSnapshot> {
  const customer = await getDb().select().from(customers).where(eq(customers.userId, userId)).get();
  const status = (customer?.subscriptionStatus ?? "none") as SubscriptionStatus;
  return {
    status,
    live: isLiveSubscription(status),
    access: grantsAccess(status),
    planId: customer?.planId ?? null,
    endsAt: customer?.subscriptionEndsAt ? new Date(customer.subscriptionEndsAt) : null,
    cancelAtPeriodEnd: customer?.cancelAtPeriodEnd ?? false,
  };
}

/** Active plans, cheapest first: subscriptions (with an interval) and one-time products. */
export async function availablePlans() {
  const rows = await getDb()
    .select({ id: plans.id, name: plans.name, slug: plans.slug, description: plans.description, amount: plans.amount, currency: plans.currency, interval: plans.interval, active: plans.active })
    .from(plans)
    .orderBy(asc(plans.sort), asc(plans.amount));
  const active = rows.filter((plan) => plan.active !== false);
  return { subscriptions: active.filter((plan) => plan.interval), oneTime: active.filter((plan) => !plan.interval) };
}

/** A user's one-time purchases, newest first. */
export async function userPurchases(userId: string) {
  const customer = await getDb().select({ id: customers.id }).from(customers).where(eq(customers.userId, userId)).get();
  if (!customer) return [];
  return getDb()
    .select({ id: purchases.id, status: purchases.status, amount: purchases.amount, currency: purchases.currency, createdAt: purchases.createdAt, plan: plans.name })
    .from(purchases)
    .leftJoin(plans, eq(purchases.planId, plans.id))
    .where(eq(purchases.customerId, customer.id))
    .orderBy(desc(purchases.createdAt));
}
`;

/** `app/api/billing/checkout/route.ts`: start Checkout for a new subscription or a one-time purchase. */
export const renderCheckoutRoute = (): string => `import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { isLiveSubscription, randomLetters } from "@flare/core";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { getSession } from "@/lib/session";
import { appOrigin, createStripe, getOrCreateCustomer } from "@/lib/stripe";

/**
 * POST { planSlug }. The plan decides the mode: a recurring price starts a
 * subscription, a one-time price a payment. Prices only ever come from the Plan
 * table, so a client can't pay for an arbitrary price. A customer who already has
 * a subscription changes plans through the portal instead of buying a second one.
 */
export async function POST(request: NextRequest) {
  const raw = await request.text();
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Sign in to check out." }, { status: 401 });

  let planSlug = "";
  try {
    planSlug = String((JSON.parse(raw) as { planSlug?: unknown }).planSlug ?? "");
  } catch {
    return NextResponse.json({ error: "Send JSON like {\\"planSlug\\": \\"pro\\"}." }, { status: 400 });
  }
  const plan = planSlug ? await getDb().select().from(plans).where(eq(plans.slug, planSlug)).get() : undefined;
  if (!plan || plan.active === false) return NextResponse.json({ error: "That plan isn't available." }, { status: 404 });

  const mode = plan.interval ? "subscription" : "payment";
  const customer = await getOrCreateCustomer(session.user);
  if (mode === "subscription" && isLiveSubscription(customer.subscriptionStatus)) {
    return NextResponse.json({ error: "You already have a subscription. Change plans from the billing page." }, { status: 409 });
  }

  const base = appOrigin(request);
  const checkout = await createStripe().checkout.sessions.create({
    mode,
    line_items: [{ price: plan.stripePriceId, quantity: 1 }],
    customer: customer.stripeCustomerId,
    client_reference_id: customer.id,
    integration_identifier: \`flare-billing-\${randomLetters()}\`,
    success_url: \`\${base}/dashboard/billing?checkout=success&session_id={CHECKOUT_SESSION_ID}\`,
    cancel_url: \`\${base}/dashboard/billing?checkout=cancelled\`,
  });
  if (!checkout.url) return NextResponse.json({ error: "Stripe did not return a checkout URL." }, { status: 502 });
  return NextResponse.json({ url: checkout.url });
}
`;

/** `app/api/billing/portal/route.ts`: the Stripe Customer Portal, optionally straight to a plan change. */
export const renderPortalRoute = (): string => `import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { isLiveSubscription } from "@flare/core";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { getSession } from "@/lib/session";
import { appOrigin, billingPortalConfiguration, createStripe, getOrCreateCustomer } from "@/lib/stripe";

/**
 * POST {} opens the portal (payment methods, invoices, cancel). POST { planSlug }
 * opens its plan-change confirmation for that plan: Stripe shows the prorated
 * amount and applies the change to the existing subscription, so switching plans
 * never starts a second one.
 */
export async function POST(request: NextRequest) {
  const raw = await request.text();
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Sign in to manage billing." }, { status: 401 });

  let planSlug = "";
  try {
    planSlug = raw ? String((JSON.parse(raw) as { planSlug?: unknown }).planSlug ?? "") : "";
  } catch {
    return NextResponse.json({ error: "Send JSON like {\\"planSlug\\": \\"pro\\"}, or no body." }, { status: 400 });
  }

  const customer = await getOrCreateCustomer(session.user);
  const stripe = createStripe();
  const returnUrl = \`\${appOrigin(request)}/dashboard/billing\`;

  const configuration = await billingPortalConfiguration(stripe);

  if (!planSlug) {
    const portal = await stripe.billingPortal.sessions.create({ customer: customer.stripeCustomerId, return_url: returnUrl, configuration });
    return NextResponse.json({ url: portal.url });
  }

  const plan = await getDb().select().from(plans).where(eq(plans.slug, planSlug)).get();
  if (!plan || plan.active === false || !plan.interval) return NextResponse.json({ error: "That plan isn't available." }, { status: 404 });
  if (!customer.stripeSubscriptionId || !isLiveSubscription(customer.subscriptionStatus)) {
    return NextResponse.json({ error: "You don't have a subscription to change yet. Subscribe first." }, { status: 409 });
  }
  const subscription = await stripe.subscriptions.retrieve(customer.stripeSubscriptionId);
  const item = subscription.items.data[0];
  if (!item) return NextResponse.json({ error: "The subscription has no items to change." }, { status: 409 });

  const portal = await stripe.billingPortal.sessions.create({
    customer: customer.stripeCustomerId,
    return_url: returnUrl,
    configuration,
    flow_data: {
      type: "subscription_update_confirm",
      subscription_update_confirm: {
        subscription: subscription.id,
        items: [{ id: item.id, price: plan.stripePriceId, quantity: 1 }],
      },
      after_completion: { type: "redirect", redirect: { return_url: \`\${returnUrl}?changed=1\` } },
    },
  });
  return NextResponse.json({ url: portal.url });
}
`;

/** `app/api/webhooks/stripe/route.ts`: signature-verified events that keep billing state in sync. */
export const renderWebhookRoute = (): string => `import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { createStripe, failCheckoutSession, invoiceSubscriptionId, stripeSecrets, syncCheckoutSession, syncSubscription } from "@/lib/stripe";

/**
 * Stripe calls this, so it has no session: the signature is the authentication.
 * Point a webhook endpoint at /api/webhooks/stripe with these events:
 *   checkout.session.completed, checkout.session.async_payment_succeeded,
 *   checkout.session.async_payment_failed, customer.subscription.created,
 *   customer.subscription.updated, customer.subscription.deleted,
 *   customer.subscription.paused, customer.subscription.resumed,
 *   invoice.paid, invoice.payment_failed
 */
export async function POST(request: NextRequest) {
  // The raw body: the signature covers these exact bytes.
  const payload = await request.text();
  const { STRIPE_WEBHOOK_SECRET } = stripeSecrets();
  if (!STRIPE_WEBHOOK_SECRET) {
    return NextResponse.json({ error: "STRIPE_WEBHOOK_SECRET is not set." }, { status: 501 });
  }
  const signature = request.headers.get("stripe-signature");
  if (!signature) return NextResponse.json({ error: "Missing stripe-signature header." }, { status: 400 });

  let event: Stripe.Event;
  try {
    // Workers only offer async (SubtleCrypto) HMAC, so the async variant is required here.
    event = await createStripe().webhooks.constructEventAsync(payload, signature, STRIPE_WEBHOOK_SECRET, undefined, Stripe.createSubtleCryptoProvider());
  } catch {
    return NextResponse.json({ error: "Invalid signature." }, { status: 400 });
  }

  // Each handler re-fetches the object from Stripe, so duplicates and
  // out-of-order deliveries are harmless. A thrown error returns 500 and Stripe retries.
  switch (event.type) {
    case "checkout.session.completed":
    case "checkout.session.async_payment_succeeded":
      await syncCheckoutSession(event.data.object.id);
      break;
    case "checkout.session.async_payment_failed":
      await failCheckoutSession(event.data.object.id);
      break;
    case "customer.subscription.created":
    case "customer.subscription.updated":
    case "customer.subscription.deleted":
    case "customer.subscription.paused":
    case "customer.subscription.resumed":
      await syncSubscription(event.data.object.id);
      break;
    case "invoice.paid":
    case "invoice.payment_failed": {
      const subscriptionId = invoiceSubscriptionId(event.data.object);
      if (subscriptionId) await syncSubscription(subscriptionId);
      break;
    }
  }
  return NextResponse.json({ received: true });
}
`;

/** `components/billing/billing-button.tsx`: POST to a billing route and follow the Stripe URL it returns. */
export const renderBillingButton = (): string => `"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";

/**
 * Starts a Stripe flow: Checkout (\`/api/billing/checkout\`) or the portal
 * (\`/api/billing/portal\`), optionally for one plan. Errors show under the button.
 */
export function BillingButton({
  endpoint,
  planSlug,
  variant = "default",
  children,
}: {
  endpoint: "/api/billing/checkout" | "/api/billing/portal";
  planSlug?: string;
  variant?: "default" | "outline" | "secondary";
  children: React.ReactNode;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function start() {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(planSlug ? { planSlug } : {}),
      });
      const data = (await response.json().catch(() => null)) as { url?: string; error?: string } | null;
      if (!response.ok || !data?.url) {
        setError(data?.error ?? "Stripe could not be reached. Try again in a moment.");
        setBusy(false);
        return;
      }
      window.location.assign(data.url);
    } catch {
      setError("Stripe could not be reached. Try again in a moment.");
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col items-start gap-2">
      <Button onClick={start} disabled={busy} variant={variant}>
        {busy && <Spinner data-icon="inline-start" />}
        {children}
      </Button>
      {error && (
        <p role="alert" className="text-sm text-destructive">
          {error}
        </p>
      )}
    </div>
  );
}
`;

/** `components/billing/billing-portal-button.tsx`: the named button the spec asks for. */
export const renderBillingPortalButton = (): string => `"use client";

import { BillingButton } from "./billing-button";

/** Opens the Stripe Customer Portal: payment methods, invoices, and cancellation. */
export function BillingPortalButton({ children = "Manage billing" }: { children?: React.ReactNode }) {
  return (
    <BillingButton endpoint="/api/billing/portal" variant="outline">
      {children}
    </BillingButton>
  );
}
`;

/** `app/dashboard/billing/page.tsx`: subscribe, change plan, cancel, and buy once, all from one page. */
export const renderBillingPage = (): string => `import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { BillingButton } from "@/components/billing/billing-button";
import { BillingPortalButton } from "@/components/billing/billing-portal-button";
import { requireSession } from "@/lib/session";
import { availablePlans, billingSnapshot, userPurchases } from "@/lib/billing";

const STATUS: Record<string, { label: string; tone: "secondary" | "success" | "warning" | "danger" }> = {
  none: { label: "No subscription", tone: "secondary" },
  incomplete: { label: "Payment pending", tone: "warning" },
  trialing: { label: "Trial", tone: "success" },
  active: { label: "Active", tone: "success" },
  past_due: { label: "Payment failed, retrying", tone: "warning" },
  paused: { label: "Paused", tone: "secondary" },
  canceled: { label: "Canceled", tone: "secondary" },
  unpaid: { label: "Unpaid", tone: "danger" },
};

const money = (cents: number, currency: string) =>
  new Intl.NumberFormat(undefined, { style: "currency", currency: currency.toUpperCase() }).format(cents / 100);
const day = (date: Date) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(date);

export default async function BillingPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requireSession("/dashboard/billing");
  const [billing, { subscriptions, oneTime }, purchases, params] = await Promise.all([
    billingSnapshot(session.user.id),
    availablePlans(),
    userPurchases(session.user.id),
    searchParams,
  ]);
  const status = STATUS[billing.status] ?? STATUS.none!;
  const current = subscriptions.find((plan) => billing.live && plan.id === billing.planId);

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-col gap-8 px-4 py-10">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold">Billing</h1>
          <p className="text-sm text-muted-foreground">
            {current
              ? billing.cancelAtPeriodEnd && billing.endsAt
                ? \`\${current.name} ends on \${day(billing.endsAt)}.\`
                : billing.endsAt
                  ? \`\${current.name} renews on \${day(billing.endsAt)}.\`
                  : \`You're on \${current.name}.\`
              : "Choose a plan to get started."}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Badge variant={status.tone}>{status.label}</Badge>
          {billing.live && <BillingPortalButton />}
        </div>
      </div>

      {params.checkout === "success" && (
        <Alert>
          <AlertDescription>Payment received. Your plan updates here as soon as Stripe confirms it, usually within seconds.</AlertDescription>
        </Alert>
      )}

      {subscriptions.length > 0 && (
        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-medium">Plans</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {subscriptions.map((plan) => {
              const isCurrent = plan.id === current?.id;
              return (
                <Card key={plan.id} className={isCurrent ? "border-primary" : undefined}>
                  <CardHeader>
                    <CardTitle>{plan.name}</CardTitle>
                    <CardDescription>
                      {money(plan.amount, plan.currency)} per {plan.interval}
                    </CardDescription>
                  </CardHeader>
                  {plan.description && <CardContent className="text-sm text-muted-foreground">{plan.description}</CardContent>}
                  <CardFooter>
                    {isCurrent ? (
                      <span className="text-sm text-muted-foreground">Your current plan</span>
                    ) : billing.live ? (
                      <BillingButton endpoint="/api/billing/portal" planSlug={plan.slug} variant="outline">
                        Switch to {plan.name}
                      </BillingButton>
                    ) : (
                      <BillingButton endpoint="/api/billing/checkout" planSlug={plan.slug}>
                        Subscribe
                      </BillingButton>
                    )}
                  </CardFooter>
                </Card>
              );
            })}
          </div>
        </section>
      )}

      {oneTime.length > 0 && (
        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-medium">Buy once</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {oneTime.map((plan) => (
              <Card key={plan.id}>
                <CardHeader>
                  <CardTitle>{plan.name}</CardTitle>
                  <CardDescription>{money(plan.amount, plan.currency)}, one-time</CardDescription>
                </CardHeader>
                {plan.description && <CardContent className="text-sm text-muted-foreground">{plan.description}</CardContent>}
                <CardFooter>
                  <BillingButton endpoint="/api/billing/checkout" planSlug={plan.slug} variant="outline">
                    Buy {plan.name}
                  </BillingButton>
                </CardFooter>
              </Card>
            ))}
          </div>
        </section>
      )}

      {subscriptions.length === 0 && oneTime.length === 0 && (
        <p className="text-sm text-muted-foreground">
          No plans yet. Create products in Stripe, then run <code>flare billing:sync-plans</code>.
        </p>
      )}

      {purchases.length > 0 && (
        <section className="flex flex-col gap-2">
          <h2 className="text-sm font-medium">Purchases</h2>
          <ul className="flex flex-col divide-y rounded-lg border text-sm">
            {purchases.map((purchase) => (
              <li key={purchase.id} className="flex items-center justify-between gap-4 px-4 py-3">
                <span className="truncate">{purchase.plan ?? "One-time purchase"}</span>
                <span className="flex items-center gap-3 tabular-nums text-muted-foreground">
                  {money(purchase.amount, purchase.currency)}
                  <Badge variant={purchase.status === "paid" ? "success" : purchase.status === "failed" ? "danger" : "warning"}>
                    {purchase.status === "paid" ? "Paid" : purchase.status === "failed" ? "Failed" : "Pending"}
                  </Badge>
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <Link href="/dashboard" className="text-sm text-muted-foreground underline underline-offset-4">
        Back to the dashboard
      </Link>
    </main>
  );
}
`;

/** Empty .dev.vars entries (declaring them also types them via `wrangler types`). */
export const billingDevVarsEntries = (): string => "STRIPE_SECRET_KEY=\nSTRIPE_WEBHOOK_SECRET=\n";

/** Documented entries for `.dev.vars.example`. */
export const billingDevVarsExampleEntries = (): string =>
  [
    "",
    "# Stripe. Use a restricted key (rk_test_ / rk_live_) with write access to",
    "# Customers, Checkout Sessions and Customer portal, and read access to",
    "# Subscriptions, Products and Prices. Test in a Stripe sandbox, never with live keys.",
    "# Production: wrangler secret put STRIPE_SECRET_KEY",
    "STRIPE_SECRET_KEY=",
    "# The signing secret of the webhook endpoint pointing at <app URL>/api/webhooks/stripe.",
    "# Locally: stripe listen --forward-to localhost:8787/api/webhooks/stripe prints one.",
    "STRIPE_WEBHOOK_SECRET=",
    "",
  ].join("\n");
