import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import pc from "picocolors";
import { templatesDir } from "../utils/fs.js";
import type { LoadedResource } from "./load.js";
import { DriftError, inspectGenerated, writeGenerated, type FileStatus } from "./markers.js";
import type { LoadedPolicy } from "./policy.js";
import { renderPolicyRegistry } from "./policy.js";
import { renderRegistry, renderRelations, renderSchemaIndex, renderServerRegistry, resourceFiles } from "./render.js";

export interface PlannedFile {
  /** Relative to the app root. */
  path: string;
  content: string;
  header?: string;
}

export const resourceHeader = (name: string) =>
  `// Generated by \`flare gen resource ${name}\`. Code inside the generated block is\n` +
  `// rewritten on regeneration; add your own code outside it.\n`;

const HEADER_PATTERN = /^\/\/ Generated by `flare gen resource (\w+)`/;

/** Every derived file for every resource, plus the shared relations, registry, and schema index. */
export function planFiles(all: LoadedResource[], policies?: LoadedPolicy[]): PlannedFile[] {
  const files: PlannedFile[] = [];
  for (const entry of all) {
    for (const file of resourceFiles(entry, all)) files.push({ ...file, header: resourceHeader(entry.resource.name) });
  }
  files.push(
    { path: "db/relations.ts", content: renderRelations(all), header: "// Drizzle relations for every resource (maintained by flare gen).\n" },
    { path: "resources/index.ts", content: renderRegistry(all), header: "// Registry of every resource descriptor (maintained by flare gen).\n" },
    {
      path: "resources/server.ts",
      content: renderServerRegistry(all),
      header: "// Server-only: resource name → descriptor and table (maintained by flare gen).\n",
    },
    { path: "db/schema.ts", content: renderSchemaIndex(all) },
  );
  // Only when the caller loaded policies: commands that don't (`gen resource`) leave the registry alone.
  if (policies) {
    files.push({
      path: "policies/index.ts",
      content: renderPolicyRegistry(policies),
      header: "// Registry of every resource policy (maintained by flare gen policy).\n",
    });
  }
  return files;
}

export type Outcome = "create" | "update" | "identical" | "skipped-drift" | "skipped-unmarked";

export interface FileResult {
  path: string;
  status: FileStatus;
  outcome: Outcome;
}

/** Inspect (dryRun) or write planned files. Drifted and hand-written files are skipped, never thrown. */
export function applyPlan(appRoot: string, plan: PlannedFile[], options: { force?: boolean; dryRun?: boolean } = {}): FileResult[] {
  return plan.map(({ path, content, header }) => {
    const absolute = join(appRoot, path);
    const status = inspectGenerated(absolute, content);
    if (status === "unmarked") return { path, status, outcome: "skipped-unmarked" };
    if (status === "drift" && !options.force) return { path, status, outcome: "skipped-drift" };
    if (options.dryRun) {
      const outcome = status === "missing" ? "create" : status === "identical" ? "identical" : "update";
      return { path, status, outcome };
    }
    try {
      return { path, status, outcome: writeGenerated(absolute, content, { header, force: options.force }) };
    } catch (error) {
      if (error instanceof DriftError) return { path, status: "drift", outcome: "skipped-drift" };
      throw error;
    }
  });
}

/**
 * Resource-owned generated files (found by their header) that the current plan no longer
 * produces: the resource was deleted, or its table/slug was renamed.
 */
export function findOrphans(appRoot: string, all: LoadedResource[]): { path: string; resource: string }[] {
  const planned = new Set(planFiles(all).map((file) => file.path));
  const candidates: string[] = [];
  const list = (dir: string, match: (name: string) => boolean) =>
    existsSync(join(appRoot, dir)) ? readdirSync(join(appRoot, dir)).filter(match).map((name) => `${dir}/${name}`) : [];

  candidates.push(...list("db/schema", (name) => name.endsWith(".ts")));
  candidates.push(...list("resources", (name) => /\.(client|validators)\.ts$/.test(name)));
  for (const dir of list("app/api", () => true)) {
    for (const file of [`${dir}/route.ts`, `${dir}/[id]/route.ts`]) if (existsSync(join(appRoot, file))) candidates.push(file);
  }
  for (const dir of list("app/admin", () => true)) {
    for (const file of [`${dir}/page.tsx`, `${dir}/new/page.tsx`, `${dir}/[id]/edit/page.tsx`]) {
      if (existsSync(join(appRoot, file))) candidates.push(file);
    }
  }

  const orphans: { path: string; resource: string }[] = [];
  for (const path of candidates) {
    const match = HEADER_PATTERN.exec(readFileSync(join(appRoot, path), "utf8"));
    if (match && !planned.has(path)) orphans.push({ path, resource: match[1]! });
  }
  return orphans;
}

/** Files every app needs once resources exist (copied from the app template if missing). */
export function ensureSupportFiles(appRoot: string, log: (message: string) => void) {
  for (const path of ["lib/api.ts", "lib/cache.ts"]) {
    const target = join(appRoot, path);
    if (existsSync(target)) continue;
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(join(templatesDir, "app", path), target);
    log(`${pc.green("create".padEnd(9))} ${path}`);
  }
}

export function logResults(results: FileResult[], log: (message: string) => void, options: { showIdentical?: boolean } = {}) {
  for (const { path, outcome } of results) {
    if (outcome === "identical" && !options.showIdentical) continue;
    const label =
      outcome === "create"
        ? pc.green("create")
        : outcome === "update"
          ? pc.yellow("update")
          : outcome === "identical"
            ? pc.dim("identical")
            : pc.red(outcome === "skipped-drift" ? "drift" : "hand-written");
    log(`${label.padEnd(18)} ${path}`);
  }
}
