import { applyEdits, modify, parse as parseJsonc } from "jsonc-parser";
import { renderDescriptor } from "./descriptor.js";
import { parseFields } from "./grammar.js";

/**
 * `flare gen security` scaffolding: security.config.ts, the SecurityEvent resource,
 * lib/security.ts (the Worker-layer guard, wired into worker/index.ts), the
 * /admin/security dashboard, and the wrangler bindings the guard needs.
 */

export const SECURITY_EVENT_FIELDS =
  "kind:string, severity:enum(low,medium,high), ip:string, path:string, userAgent:text?, count:int, banned:boolean?, detail:text?";

export const renderSecurityDescriptor = (): string => renderDescriptor("SecurityEvent", parseFields(SECURITY_EVENT_FIELDS));

/** Security events are evidence: anyone on staff can read them, only admins change them. */
export const SECURITY_EVENT_POLICY = { read: ["admin", "staff"], create: ["admin"], update: ["admin"], delete: ["admin"] };

export const securityHeader = () =>
  `// Generated by \`flare gen security\`. Code inside the generated block is\n` +
  `// rewritten on regeneration; add your own code outside it.\n`;

/** `security.config.ts`: the app's own file, written once and never overwritten. */
export const renderSecurityConfig = (): string => `import { DEFAULT_DETECTORS, defineSecurity } from "@flare/core/security";

/**
 * What Flare watches for and blocks. The Worker layer applies this on every request
 * (any plan, workers.dev included). The \`zone\` rules are pushed to your zone by
 * \`flare deploy\` when FLARE_SECURITY_ZONE_ID and FLARE_SECURITY_API_TOKEN are set.
 */
export default defineSecurity({
  // IPs never banned or rate-limited: your office, uptime monitors.
  allow: [],

  // Failed-login bursts, checkout abuse and API scraping. Each trip is logged as a
  // SecurityEvent; detectors with \`ban\` also block the IP.
  detectors: DEFAULT_DETECTORS,

  // Worker-level rate limit for the API (limit and period are set on the
  // FLARE_RATE_LIMIT binding in wrangler.jsonc).
  rateLimit: { binding: "FLARE_RATE_LIMIT", paths: /^\\/api\\// },

  zone: {
    // The Free plan allows one rate-limiting rule, with a 10-second period.
    rateLimits: [
      {
        name: "sign-in",
        expression: 'http.request.uri.path eq "/api/auth/sign-in/email"',
        requests: 10,
        periodSeconds: 10,
        mitigationSeconds: 10,
      },
    ],
    customRules: [
      {
        name: "block-scanners",
        expression:
          '(http.request.uri.path contains "/wp-login.php") or (http.request.uri.path contains "/xmlrpc.php") or (http.request.uri.path contains "/.env") or (http.request.uri.path contains "/.git/")',
        action: "block",
      },
    ],
  },
});
`;

/** `lib/security.ts`: the Worker-layer guard, built from the app's bindings and config. */
export const renderLibSecurity = (app: string): string => `import { env as runtimeEnv } from "cloudflare:workers";
import { createZoneClient } from "@flare/core/security";
import { createSecurity, type BanStore, type MonitorNamespace, type RateLimiter, type Security } from "@flare/core/security/server";
import { getDb } from "../db";
import { securityEvents } from "../db/schema";
import config from "../security.config";

/** Minimal ExecutionContext surface worker/index.ts passes in. */
export interface SecurityContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface SecurityEnv {
  FLARE_SECURITY: BanStore;
  FLARE_SECURITY_MONITOR: MonitorNamespace;
  FLARE_RATE_LIMIT?: RateLimiter;
  /** With both set (wrangler secrets), bans also become zone IP Access Rules. */
  FLARE_SECURITY_ZONE_ID?: string;
  FLARE_SECURITY_API_TOKEN?: string;
}

/** This app's tag on zone rules, so Flare only ever changes its own. */
const APP = ${JSON.stringify(app)};

const bindings = () => runtimeEnv as unknown as SecurityEnv;
let instance: Security | undefined;

/** The app's security layer, one per isolate. */
export function security(): Security {
  const env = bindings();
  instance ??= createSecurity({
    config,
    bans: env.FLARE_SECURITY,
    monitors: env.FLARE_SECURITY_MONITOR,
    rateLimiter: env.FLARE_RATE_LIMIT,
    zone: zoneClient(),
    // Every tripped detector becomes a SecurityEvent row.
    onTrip: (trip) =>
      logSecurityEvent({
        kind: trip.detector.name,
        severity: trip.detector.severity ?? "medium",
        ip: trip.ip,
        path: trip.path,
        userAgent: trip.userAgent,
        count: trip.count,
        banned: trip.banned,
        detail: trip.detector.description ?? null,
      }),
  });
  return instance;
}

/** The zone layer, when this app has a zone and a scoped API token configured. */
export function zoneClient() {
  const env = bindings();
  return env.FLARE_SECURITY_ZONE_ID && env.FLARE_SECURITY_API_TOKEN
    ? createZoneClient({ zoneId: env.FLARE_SECURITY_ZONE_ID, apiToken: env.FLARE_SECURITY_API_TOKEN, app: APP })
    : null;
}

export async function logSecurityEvent(event: typeof securityEvents.$inferInsert): Promise<void> {
  await getDb().insert(securityEvents).values(event);
}

/** Called by worker/index.ts for every request. */
export function protect(request: Request, _env: unknown, ctx: SecurityContext, next: () => Promise<Response>): Promise<Response> {
  return security().protect(request, ctx, next);
}
`;

/** `app/admin/security/actions.ts`: manual ban and unban (admins only). */
export const renderSecurityActions = (): string => `"use server";

import { revalidatePath } from "next/cache";
import { can } from "@flare/core";
import { isIp } from "@flare/core/security";
import { adminSession, policyFor } from "@/lib/admin";
import { logSecurityEvent, security } from "@/lib/security";

/** On failure the submitted values come back, so the form (which React resets) keeps them. */
export type BanResult = { ok: true } | { ok: false; error: string; ip?: string; reason?: string };

const DURATIONS: Record<string, number | null> = { "1h": 3600, "24h": 86_400, "7d": 604_800, permanent: null };

async function adminOnly(): Promise<{ email: string } | { error: string }> {
  const { session, role } = await adminSession();
  if (!session) return { error: "Sign in required." };
  if (!can(policyFor("SecurityEvent"), role, "create")) return { error: "Only admins can ban or unban." };
  return { email: session.user.email };
}

/** Ban an IP at every layer this app has (Worker, and the zone when configured). */
export async function banAction(_previous: BanResult | null, form: FormData): Promise<BanResult> {
  const admin = await adminOnly();
  if ("error" in admin) return { ok: false, error: admin.error };
  const ip = String(form.get("ip") ?? "").trim();
  const reason = String(form.get("reason") ?? "").trim() || "Banned manually";
  const duration = String(form.get("duration") ?? "24h");
  if (!isIp(ip)) return { ok: false, error: \`"\${ip}" isn't an IP address.\`, ip, reason };
  if (!(duration in DURATIONS)) return { ok: false, error: "Choose how long to ban for.", ip, reason };

  try {
    await security().ban(ip, \`\${reason} (by \${admin.email})\`, DURATIONS[duration]!, null);
  } catch (error) {
    return { ok: false, error: \`The ban didn't reach every layer: \${error instanceof Error ? error.message : String(error)}\`, ip, reason };
  }
  await logSecurityEvent({ kind: "manual-ban", severity: "medium", ip, path: "/admin/security", userAgent: null, count: 0, banned: true, detail: \`\${reason} (by \${admin.email})\` });
  revalidatePath("/admin/security");
  return { ok: true };
}

export async function unbanAction(ip: string): Promise<BanResult> {
  const admin = await adminOnly();
  if ("error" in admin) return { ok: false, error: admin.error };
  if (!isIp(ip)) return { ok: false, error: \`"\${ip}" isn't an IP address.\` };
  try {
    await security().unban(ip);
  } catch (error) {
    return { ok: false, error: \`The unban didn't reach every layer: \${error instanceof Error ? error.message : String(error)}\` };
  }
  await logSecurityEvent({ kind: "manual-unban", severity: "low", ip, path: "/admin/security", userAgent: null, count: 0, banned: false, detail: \`by \${admin.email}\` });
  revalidatePath("/admin/security");
  return { ok: true };
}
`;

/** `app/admin/security/ban-controls.tsx`: the client-side ban form and unban buttons. */
export const renderBanControls = (): string => `"use client";

import { useActionState, useState, useTransition } from "react";
import { toast } from "sonner";
import { banAction, unbanAction, type BanResult } from "./actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";

const DURATIONS = { "1h": "1 hour", "24h": "24 hours", "7d": "7 days", permanent: "Until unbanned" } as const;

export function BanForm() {
  const [state, action, pending] = useActionState<BanResult | null, FormData>(banAction, null);
  const [duration, setDuration] = useState<keyof typeof DURATIONS>("24h");
  return (
    <form action={action}>
      <FieldGroup className="gap-4">
        <div className="grid gap-4 sm:grid-cols-[1fr_12rem_auto] sm:items-end">
          <Field data-invalid={state && !state.ok ? true : undefined}>
            <FieldLabel htmlFor="ban-ip">IP address</FieldLabel>
            <Input id="ban-ip" name="ip" defaultValue={state && !state.ok ? state.ip : undefined} placeholder="203.0.113.7" required autoComplete="off" spellCheck={false} aria-invalid={state && !state.ok ? true : undefined} />
          </Field>
          <Field>
            <FieldLabel htmlFor="ban-duration">For</FieldLabel>
            <Select name="duration" value={duration} onValueChange={(value) => setDuration(value as keyof typeof DURATIONS)}>
              <SelectTrigger id="ban-duration" className="w-full">
                {/* Radix fills SelectValue only once the list has mounted; give it the label up front. */}
                <SelectValue>{DURATIONS[duration]}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {Object.entries(DURATIONS).map(([value, label]) => (
                    <SelectItem key={value} value={value}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </Field>
          <Button type="submit" disabled={pending}>
            {pending && <Spinner data-icon="inline-start" />}
            Ban IP
          </Button>
        </div>
        <Field>
          <FieldLabel htmlFor="ban-reason">Reason</FieldLabel>
          <Input id="ban-reason" name="reason" defaultValue={state && !state.ok ? state.reason : undefined} placeholder="Credential stuffing from this address…" autoComplete="off" />
        </Field>
        {state && !state.ok && <FieldError role="alert">{state.error}</FieldError>}
        {state?.ok && (
          <FieldDescription role="status">Banned.</FieldDescription>
        )}
      </FieldGroup>
    </form>
  );
}

export function UnbanButton({ ip }: { ip: string }) {
  const [pending, start] = useTransition();
  return (
    <Button
      variant="outline"
      size="sm"
      disabled={pending}
      onClick={() =>
        start(async () => {
          const result = await unbanAction(ip);
          if (result.ok) toast.success(\`Unbanned \${ip}.\`);
          else toast.error(result.error);
        })
      }
    >
      {pending && <Spinner data-icon="inline-start" />}
      Unban<span className="sr-only"> {ip}</span>
    </Button>
  );
}
`;

/** `app/admin/security/page.tsx`: bans, recent events, and the zone's firewall activity. */
export const renderSecurityPage = (): string => `import Link from "next/link";
import { can } from "@flare/core";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { adminStore, policyFor, requireAdmin } from "@/lib/admin";
import { security, zoneClient } from "@/lib/security";
import { BanForm, UnbanButton } from "./ban-controls";

const TONE = { high: "danger", medium: "warning", low: "secondary" } as const;
const when = (value: string | number | Date | null) =>
  value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Until unbanned";

export default async function SecurityPage() {
  const { role } = await requireAdmin("/admin/security");
  if (!can(policyFor("SecurityEvent"), role, "read")) {
    return (
      <Alert>
        <AlertDescription>Your role can't view security activity.</AlertDescription>
      </Alert>
    );
  }
  const canBan = can(policyFor("SecurityEvent"), role, "create");
  const zone = zoneClient();

  const [bans, events, edge] = await Promise.all([
    security().bans(),
    adminStore("SecurityEvent").list(new URLSearchParams({ sort: "-createdAt", perPage: "20" })),
    zone
      ? Promise.all([zone.bans(), zone.firewallEvents(new Date(Date.now() - 24 * 3600 * 1000))]).then(
          ([zoneBans, firewall]) => ({ ok: true as const, zoneBans, firewall }),
          (error: unknown) => ({ ok: false as const, error: error instanceof Error ? error.message : String(error) }),
        )
      : Promise.resolve(null),
  ]);
  const recent = events.ok ? events.data.data : [];
  const zoneIps = new Set(edge?.ok ? edge.zoneBans.map((ban) => ban.ip) : []);
  const blockedTotal = bans.reduce((sum, ban) => sum + ban.blocked, 0);

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold">Security</h1>
          <p className="text-sm text-muted-foreground">
            Worker layer on{zone ? ", zone rules on" : "; zone rules off (set FLARE_SECURITY_ZONE_ID and FLARE_SECURITY_API_TOKEN)"}.
          </p>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader>
            <CardDescription>Active bans</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">{bans.length}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Requests blocked by bans</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">{blockedTotal}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Zone firewall events, 24h</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">
              {edge?.ok ? edge.firewall.reduce((sum, row) => sum + row.count, 0) : "—"}
            </CardTitle>
          </CardHeader>
        </Card>
      </div>

      {edge && !edge.ok && (
        <Alert>
          <AlertDescription>The zone layer couldn't be read: {edge.error}</AlertDescription>
        </Alert>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Banned IPs</CardTitle>
          <CardDescription>Refused before the app runs{zone ? ", and blocked at the zone edge" : ""}.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          {bans.length === 0 ? (
            <Empty className="border border-dashed">
              <EmptyHeader>
                <EmptyTitle>No active bans</EmptyTitle>
                <EmptyDescription>IPs that trip a detector with a ban, or that you ban here, appear in this list.</EmptyDescription>
              </EmptyHeader>
            </Empty>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>IP</TableHead>
                  <TableHead>Reason</TableHead>
                  <TableHead>Blocked</TableHead>
                  <TableHead>Until</TableHead>
                  {canBan && <TableHead className="w-0" />}
                </TableRow>
              </TableHeader>
              <TableBody>
                {bans.map((ban) => (
                  <TableRow key={ban.ip}>
                    <TableCell className="font-medium tabular-nums">
                      <span className="flex items-center gap-2">
                        {ban.ip}
                        {zoneIps.has(ban.ip) && <Badge variant="secondary">zone</Badge>}
                      </span>
                    </TableCell>
                    <TableCell className="max-w-80 truncate text-muted-foreground">{ban.reason}</TableCell>
                    <TableCell className="tabular-nums">{ban.blocked}</TableCell>
                    <TableCell className="text-muted-foreground">{when(ban.until)}</TableCell>
                    {canBan && (
                      <TableCell>
                        <UnbanButton ip={ban.ip} />
                      </TableCell>
                    )}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
          {canBan && (
            <>
              <Separator />
              <BanForm />
            </>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent events</CardTitle>
          <CardDescription>
            Detectors that tripped, and manual bans. <Link href="/admin/security-events" className="underline underline-offset-4">All events</Link>
          </CardDescription>
        </CardHeader>
        <CardContent>
          {recent.length === 0 ? (
            <p className="text-sm text-muted-foreground">Nothing yet.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>When</TableHead>
                  <TableHead>Event</TableHead>
                  <TableHead>IP</TableHead>
                  <TableHead>Count</TableHead>
                  <TableHead>Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {recent.map((event) => (
                  <TableRow key={String(event.id)}>
                    <TableCell className="text-muted-foreground">{when(event.createdAt as Date)}</TableCell>
                    <TableCell>
                      <span className="flex items-center gap-2">
                        <Badge variant={TONE[event.severity as keyof typeof TONE] ?? "secondary"}>{String(event.severity)}</Badge>
                        {String(event.kind)}
                      </span>
                    </TableCell>
                    <TableCell className="tabular-nums">{String(event.ip)}</TableCell>
                    <TableCell className="tabular-nums">{Number(event.count) || "—"}</TableCell>
                    <TableCell className="text-muted-foreground">{event.banned ? "Banned" : "Logged"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {edge?.ok && (
        <Card>
          <CardHeader>
            <CardTitle>Zone firewall, last 24 hours</CardTitle>
            <CardDescription>What Cloudflare's edge did before requests reached the Worker.</CardDescription>
          </CardHeader>
          <CardContent>
            {edge.firewall.length === 0 ? (
              <p className="text-sm text-muted-foreground">No firewall events.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Action</TableHead>
                    <TableHead>Source</TableHead>
                    <TableHead>Rule</TableHead>
                    <TableHead>Events</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {edge.firewall.map((row, index) => (
                    <TableRow key={index}>
                      <TableCell>{row.action}</TableCell>
                      <TableCell className="text-muted-foreground">{row.source}</TableCell>
                      <TableCell className="text-muted-foreground">{row.description ?? "—"}</TableCell>
                      <TableCell className="tabular-nums">{row.count}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
`;

/** Add the bindings the security layer needs to wrangler.jsonc, keeping everything else. */
export function addSecurityBindings(source: string): { text: string; added: string[] } {
  const config = (parseJsonc(source) ?? {}) as {
    kv_namespaces?: Array<{ binding: string }>;
    durable_objects?: { bindings?: Array<{ name: string }> };
    migrations?: Array<{ tag: string; new_sqlite_classes?: string[]; new_classes?: string[] }>;
    ratelimits?: Array<{ name: string }>;
  };
  let text = source;
  const added: string[] = [];
  const format = { formattingOptions: { insertSpaces: true, tabSize: 2 } };
  const append = (path: (string | number)[], value: unknown) => {
    text = applyEdits(text, modify(text, path, value, { ...format, isArrayInsertion: true }));
  };

  if (!config.kv_namespaces?.some((entry) => entry.binding === "FLARE_SECURITY")) {
    if (config.kv_namespaces) append(["kv_namespaces", config.kv_namespaces.length], { binding: "FLARE_SECURITY" });
    else text = applyEdits(text, modify(text, ["kv_namespaces"], [{ binding: "FLARE_SECURITY" }], format));
    added.push("kv_namespaces: FLARE_SECURITY (ban list)");
  }
  if (!config.durable_objects?.bindings?.some((entry) => entry.name === "FLARE_SECURITY_MONITOR")) {
    const binding = { name: "FLARE_SECURITY_MONITOR", class_name: "SecurityMonitor" };
    if (config.durable_objects?.bindings) append(["durable_objects", "bindings", config.durable_objects.bindings.length], binding);
    else text = applyEdits(text, modify(text, ["durable_objects", "bindings"], [binding], format));
    added.push("durable_objects: FLARE_SECURITY_MONITOR (per-IP counters)");
  }
  const classes = (config.migrations ?? []).flatMap((migration) => [...(migration.new_sqlite_classes ?? []), ...(migration.new_classes ?? [])]);
  if (!classes.includes("SecurityMonitor")) {
    const migration = { tag: "flare-security-v1", new_sqlite_classes: ["SecurityMonitor"] };
    if (config.migrations) append(["migrations", config.migrations.length], migration);
    else text = applyEdits(text, modify(text, ["migrations"], [migration], format));
    added.push("migrations: SecurityMonitor");
  }
  if (!config.ratelimits?.some((entry) => entry.name === "FLARE_RATE_LIMIT")) {
    // namespace_id is any number unique within the account; a random one avoids clashing with other apps.
    const binding = { name: "FLARE_RATE_LIMIT", namespace_id: String(1000 + Math.floor(Math.random() * 9000)), simple: { limit: 120, period: 60 } };
    if (config.ratelimits) append(["ratelimits", config.ratelimits.length], binding);
    else text = applyEdits(text, modify(text, ["ratelimits"], [binding], format));
    added.push("ratelimits: FLARE_RATE_LIMIT (120 requests/minute per IP on /api)");
  }
  return { text, added };
}

/** The generated block of lib/admin-nav.ts, with the Security link. */
export const renderAdminNavBlock = (): string => `export interface AdminLink {
  label: string;
  href: string;
  /** A resource icon name, e.g. "shield" (see components/admin/resource-icon.tsx). */
  icon: string;
}

export const generatedAdminLinks: AdminLink[] = [{ label: "Security", href: "/admin/security", icon: "shield" }];
`;
