// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1657c0b9fde7
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import securityEventResource from "@/resources/security-event.resource";

export default function NewSecurityEventPage() {
  return <ResourceFormPage resource={securityEventResource} />;
}
// generated:end
