// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=ffb6af01d26e
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { purchases } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import purchaseResource from "@/resources/purchase.resource";

const handlers = createResourceHandlers({
  resource: purchaseResource,
  table: purchases,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
