// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=eee8f0c5f637
import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { createStripe, failCheckoutSession, invoiceSubscriptionId, stripeSecrets, syncCheckoutSession, syncSubscription } from "@/lib/stripe";

/**
 * Stripe calls this, so it has no session: the signature is the authentication.
 * Point a webhook endpoint at /api/webhooks/stripe with these events:
 *   checkout.session.completed, checkout.session.async_payment_succeeded,
 *   checkout.session.async_payment_failed, customer.subscription.created,
 *   customer.subscription.updated, customer.subscription.deleted,
 *   customer.subscription.paused, customer.subscription.resumed,
 *   invoice.paid, invoice.payment_failed
 */
export async function POST(request: NextRequest) {
  // The raw body: the signature covers these exact bytes.
  const payload = await request.text();
  const { STRIPE_WEBHOOK_SECRET } = stripeSecrets();
  if (!STRIPE_WEBHOOK_SECRET) {
    return NextResponse.json({ error: "STRIPE_WEBHOOK_SECRET is not set." }, { status: 501 });
  }
  const signature = request.headers.get("stripe-signature");
  if (!signature) return NextResponse.json({ error: "Missing stripe-signature header." }, { status: 400 });

  let event: Stripe.Event;
  try {
    // Workers only offer async (SubtleCrypto) HMAC, so the async variant is required here.
    event = await createStripe().webhooks.constructEventAsync(payload, signature, STRIPE_WEBHOOK_SECRET, undefined, Stripe.createSubtleCryptoProvider());
  } catch {
    return NextResponse.json({ error: "Invalid signature." }, { status: 400 });
  }

  // Each handler re-fetches the object from Stripe, so duplicates and
  // out-of-order deliveries are harmless. A thrown error returns 500 and Stripe retries.
  switch (event.type) {
    case "checkout.session.completed":
    case "checkout.session.async_payment_succeeded":
      await syncCheckoutSession(event.data.object.id);
      break;
    case "checkout.session.async_payment_failed":
      await failCheckoutSession(event.data.object.id);
      break;
    case "customer.subscription.created":
    case "customer.subscription.updated":
    case "customer.subscription.deleted":
    case "customer.subscription.paused":
    case "customer.subscription.resumed":
      await syncSubscription(event.data.object.id);
      break;
    case "invoice.paid":
    case "invoice.payment_failed": {
      const subscriptionId = invoiceSubscriptionId(event.data.object);
      if (subscriptionId) await syncSubscription(subscriptionId);
      break;
    }
  }
  return NextResponse.json({ received: true });
}
// generated:end
