// Generated by `flare gen security`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=4e11b32f709a
"use client";

import { useActionState, useState, useTransition } from "react";
import { toast } from "sonner";
import { banAction, unbanAction, type BanResult } from "./actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";

const DURATIONS = { "1h": "1 hour", "24h": "24 hours", "7d": "7 days", permanent: "Until unbanned" } as const;

export function BanForm() {
  const [state, action, pending] = useActionState<BanResult | null, FormData>(banAction, null);
  const [duration, setDuration] = useState<keyof typeof DURATIONS>("24h");
  return (
    <form action={action}>
      <FieldGroup className="gap-4">
        <div className="grid gap-4 sm:grid-cols-[1fr_12rem_auto] sm:items-end">
          <Field data-invalid={state && !state.ok ? true : undefined}>
            <FieldLabel htmlFor="ban-ip">IP address</FieldLabel>
            <Input id="ban-ip" name="ip" defaultValue={state && !state.ok ? state.ip : undefined} placeholder="203.0.113.7" required autoComplete="off" spellCheck={false} aria-invalid={state && !state.ok ? true : undefined} />
          </Field>
          <Field>
            <FieldLabel htmlFor="ban-duration">For</FieldLabel>
            <Select name="duration" value={duration} onValueChange={(value) => setDuration(value as keyof typeof DURATIONS)}>
              <SelectTrigger id="ban-duration" className="w-full">
                {/* Radix fills SelectValue only once the list has mounted; give it the label up front. */}
                <SelectValue>{DURATIONS[duration]}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {Object.entries(DURATIONS).map(([value, label]) => (
                    <SelectItem key={value} value={value}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </Field>
          <Button type="submit" disabled={pending}>
            {pending && <Spinner data-icon="inline-start" />}
            Ban IP
          </Button>
        </div>
        <Field>
          <FieldLabel htmlFor="ban-reason">Reason</FieldLabel>
          <Input id="ban-reason" name="reason" defaultValue={state && !state.ok ? state.reason : undefined} placeholder="Credential stuffing from this address…" autoComplete="off" />
        </Field>
        {state && !state.ok && <FieldError role="alert">{state.error}</FieldError>}
        {state?.ok && (
          <FieldDescription role="status">Banned.</FieldDescription>
        )}
      </FieldGroup>
    </form>
  );
}

export function UnbanButton({ ip }: { ip: string }) {
  const [pending, start] = useTransition();
  return (
    <Button
      variant="outline"
      size="sm"
      disabled={pending}
      onClick={() =>
        start(async () => {
          const result = await unbanAction(ip);
          if (result.ok) toast.success(`Unbanned ${ip}.`);
          else toast.error(result.error);
        })
      }
    >
      {pending && <Spinner data-icon="inline-start" />}
      Unban<span className="sr-only"> {ip}</span>
    </Button>
  );
}
// generated:end
