#!/usr/bin/env python3
"""token-diet: inspect a repository and emit what later phases need.

Usage: python3 detect.py [--root .] [--out .claude/token-diet/detect.json]
(On Windows, where only `python` is on PATH, run: python detect.py ...)

Stdlib only. Prints a compact human summary to stdout and writes full JSON to --out.
"""
import argparse, json, os, re, shutil, subprocess, sys
from collections import Counter, defaultdict

# Windows consoles default to a legacy codepage (e.g. cp1252) that can't encode
# the non-ASCII glyphs (≈, →) used in the summary below; force UTF-8 so the
# script never crashes on the final print() regardless of platform/console.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

LANG_BY_EXT = {
    ".ts": "typescript", ".tsx": "typescript", ".js": "javascript", ".jsx": "javascript",
    ".mjs": "javascript", ".cjs": "javascript", ".py": "python", ".go": "go", ".rs": "rust",
    ".java": "java", ".kt": "kotlin", ".kts": "kotlin", ".cs": "csharp", ".cpp": "cpp",
    ".cc": "cpp", ".cxx": "cpp", ".c": "c", ".h": "c", ".hpp": "cpp", ".rb": "ruby",
    ".php": "php", ".swift": "swift", ".scala": "scala", ".dart": "dart", ".lua": "lua",
    ".ex": "elixir", ".exs": "elixir", ".vue": "vue", ".svelte": "svelte",
}
# Official Claude Code code-intelligence plugins and the language-server binary each needs.
LSP = {
    "typescript": ("typescript-lsp", "typescript-language-server", "npm install -g typescript-language-server typescript"),
    "javascript": ("typescript-lsp", "typescript-language-server", "npm install -g typescript-language-server typescript"),
    "python": ("pyright-lsp", "pyright-langserver", "npm install -g pyright   # or: pipx install pyright"),
    "go": ("gopls-lsp", "gopls", "go install golang.org/x/tools/gopls@latest"),
    "rust": ("rust-analyzer-lsp", "rust-analyzer", "rustup component add rust-analyzer"),
    "java": ("jdtls-lsp", "jdtls", "see https://github.com/eclipse-jdtls/eclipse.jdt.ls"),
    "csharp": ("csharp-lsp", "csharp-ls", "dotnet tool install --global csharp-ls"),
    "cpp": ("clangd-lsp", "clangd", "install clangd via your package manager"),
    "c": ("clangd-lsp", "clangd", "install clangd via your package manager"),
    "php": ("php-lsp", "intelephense", "npm install -g intelephense"),
    "swift": ("swift-lsp", "sourcekit-lsp", "ships with the Swift toolchain / Xcode"),
    "kotlin": ("kotlin-lsp", "kotlin-lsp", "see the plugin README"),
    "lua": ("lua-lsp", "lua-language-server", "install lua-language-server via your package manager"),
}
NOISE_DIR_NAMES = {
    "dist", "build", "out", "vendor", "third_party", "third-party", "generated", "__generated__",
    "gen", ".next", ".nuxt", "coverage", "target", "node_modules", "bower_components",
    "__snapshots__", "fixtures", "testdata", ".terraform", "Pods", "DerivedData", ".gradle",
    "obj", "bin", "storybook-static", ".svelte-kit", "public/build",
}
# bin/obj/fixtures/testdata can hold real code; flagged "review" instead of auto-deny.
REVIEW_DIR_NAMES = {"bin", "obj", "fixtures", "testdata", "gen", "out", "build"}
LOCKFILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "Pipfile.lock",
             "Cargo.lock", "go.sum", "composer.lock", "Gemfile.lock", "bun.lockb", "uv.lock"}
GEN_MARKERS = re.compile(rb"(@generated|Code generated .* DO NOT EDIT|DO NOT EDIT|auto-generated|autogenerated|This file was automatically generated)", re.I)
BINARYISH = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".pdf", ".zip", ".gz", ".jar",
             ".woff", ".woff2", ".ttf", ".otf", ".mp4", ".mp3", ".so", ".dylib", ".dll", ".exe",
             ".bin", ".class", ".pyc", ".lockb", ".svg"}


def sh(cmd, cwd):
    try:
        return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=120).stdout
    except Exception:
        return ""


def list_files(root):
    out = sh(["git", "ls-files", "-z"], root)
    if out:
        return [f for f in out.split("\0") if f]
    files = []
    for dp, dns, fns in os.walk(root):
        dns[:] = [d for d in dns if d not in {".git", "node_modules", ".venv", "venv", "__pycache__"}]
        for fn in fns:
            files.append(os.path.relpath(os.path.join(dp, fn), root))
    return files


def count_lines(path, limit_bytes=5_000_000):
    try:
        with open(path, "rb") as f:
            data = f.read(limit_bytes)
        return data.count(b"\n"), data[:2048]
    except Exception:
        return 0, b""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--out", default=".claude/token-diet/detect.json")
    a = ap.parse_args()
    root = os.path.abspath(a.root)
    files = list_files(root)

    lang_lines = Counter()
    area_lines = Counter()
    area_files = Counter()
    noise_dirs = defaultdict(lambda: [0, 0])  # dir -> [files, bytes]
    generated_files, minified, largest = [], [], []
    total_bytes = total_lines = 0
    claude_mds, rules = [], []

    for rel in files:
        p = os.path.join(root, rel)
        if not os.path.isfile(p):
            continue
        base = os.path.basename(rel)
        ext = os.path.splitext(base)[1].lower()
        parts = rel.split("/")
        try:
            size = os.path.getsize(p)
        except OSError:
            continue
        total_bytes += size

        if base in ("CLAUDE.md", "CLAUDE.local.md", "AGENTS.md"):
            n, _ = count_lines(p)
            claude_mds.append({"path": rel, "lines": n, "est_tokens": size // 4})
        if rel.startswith(".claude/rules/") and ext == ".md":
            head = open(p, "rb").read(600)
            rules.append({"path": rel, "path_scoped": b"paths:" in head, "est_tokens": size // 4})

        # noise directories (first matching segment)
        for i, seg in enumerate(parts[:-1]):
            if seg in NOISE_DIR_NAMES:
                d = "/".join(parts[: i + 1])
                noise_dirs[d][0] += 1
                noise_dirs[d][1] += size
                break

        if base in LOCKFILES:
            continue
        if ext in BINARYISH:
            continue
        lines, head = count_lines(p)
        total_lines += lines
        lang = LANG_BY_EXT.get(ext)
        if lang:
            lang_lines[lang] += lines
        if parts[0] in (".claude", ".github", ".vscode", ".idea"):
            continue
        area = parts[0] if len(parts) > 1 else "(root)"
        if len(parts) > 2 and parts[0] in ("packages", "apps", "services", "libs", "modules", "src", "crates", "internal", "cmd"):
            area = "/".join(parts[:2])
        area_lines[area] += lines
        area_files[area] += 1
        if GEN_MARKERS.search(head):
            generated_files.append(rel)
        if re.search(r"\.min\.(js|css)$", base) or (size > 20000 and lines < 5):
            minified.append(rel)
        largest.append((size, lines, rel))

    largest.sort(reverse=True)
    total_code_lines = sum(area_lines.values()) or 1

    # Suggested deny rules
    deny, review = [], []
    by_name = defaultdict(list)
    for d, (n, b) in noise_dirs.items():
        by_name[d.split("/")[-1]].append((d, n, b))
    for name, entries in sorted(by_name.items(), key=lambda x: -sum(e[2] for e in x[1])):
        n_tot, b_tot = sum(e[1] for e in entries), sum(e[2] for e in entries)
        target = review if name in REVIEW_DIR_NAMES else deny
        if len(entries) >= 3:  # e.g. packages/*/dist -> one glob
            target.append({"rule": f"Read(./**/{name}/**/*)", "files": n_tot, "est_tokens": b_tot // 4, "dirs": len(entries)})
        else:
            for d, n, b in entries:
                target.append({"rule": f"Read(./{d}/**/*)", "files": n, "est_tokens": b // 4})
    gen_dirs = Counter(os.path.dirname(f) for f in generated_files)
    for gd, n in gen_dirs.most_common(20):
        if n >= 3 and gd:
            deny.append({"rule": f"Read(./{gd}/**/*)", "files": n, "est_tokens": None, "reason": "files marked generated"})
    for f in generated_files:
        if gen_dirs[os.path.dirname(f)] < 3:
            deny.append({"rule": f"Read(./{f})", "files": 1, "est_tokens": None, "reason": "marked generated"})
    for f in minified[:50]:
        deny.append({"rule": f"Read(./{f})", "files": 1, "est_tokens": None, "reason": "minified"})
    present_locks = [f for f in files if os.path.basename(f) in LOCKFILES]
    for f in present_locks:
        deny.append({"rule": f"Read(./{f})", "files": 1, "est_tokens": None, "reason": "lockfile"})
    for pat in ("Read(./**/*.min.js)", "Read(./**/*.map)", "Read(./**/*.generated.*)"):
        deny.append({"rule": pat, "files": None, "est_tokens": None, "reason": "generic"})

    def covered(rule, dir_rules):
        path = rule[len("Read(./"):-1]
        for dr in dir_rules:
            prefix = dr[len("Read(./"):-len("/**/*)")]
            if prefix.startswith("**/"):
                if ("/" + prefix[3:] + "/") in ("/" + path):
                    return True
            elif path.startswith(prefix + "/"):
                return True
        return False

    dir_rules = [r["rule"] for r in deny if r["rule"].endswith("/**/*)")]
    seen, deny_unique = set(), []
    for r in deny:
        if r["rule"] in seen:
            continue
        if not r["rule"].endswith("/**/*)") and "*" not in r["rule"] and covered(r["rule"], dir_rules):
            continue
        seen.add(r["rule"]); deny_unique.append(r)

    # Test / build commands
    tests = []
    pj = os.path.join(root, "package.json")
    if os.path.exists(pj):
        try:
            scripts = json.load(open(pj)).get("scripts", {})
            for k in ("test", "lint", "build", "typecheck"):
                if k in scripts:
                    tests.append({"kind": k, "cmd": f"npm run {k}" if k != "test" else "npm test", "raw": scripts[k]})
        except Exception:
            pass
    markers = {
        "pytest.ini": "pytest", "pyproject.toml": "pytest", "setup.cfg": "pytest", "go.mod": "go test ./...",
        "Cargo.toml": "cargo test", "pom.xml": "mvn test", "build.gradle": "gradle test",
        "build.gradle.kts": "gradle test", "Gemfile": "bundle exec rspec", "composer.json": "vendor/bin/phpunit",
        "Makefile": "make test", "mix.exs": "mix test",
    }
    for m, cmd in markers.items():
        if os.path.exists(os.path.join(root, m)):
            tests.append({"kind": "test", "cmd": cmd, "detected_from": m})

    # LSP availability
    lsp = {}
    for lang, lines in lang_lines.most_common():
        if lang in LSP and lines > 0.02 * total_code_lines:
            plugin, binary, install = LSP[lang]
            lsp.setdefault(plugin, {"languages": [], "binary": binary, "installed": bool(shutil.which(binary)), "install": install})
            lsp[plugin]["languages"].append(lang)

    tools = {t: bool(shutil.which(t)) for t in ("claude", "git", "python3", "python", "node", "npm", "npx", "uv", "uvx", "pipx", "pip", "docker", "rtk", "jq")}
    settings = {s: os.path.exists(os.path.join(root, s)) for s in (".claude/settings.json", ".claude/settings.local.json", ".mcp.json")}

    root_md = next((c for c in claude_mds if c["path"] in ("CLAUDE.md", ".claude/CLAUDE.md")), None)
    always_loaded = (root_md["est_tokens"] if root_md else 0) + sum(r["est_tokens"] for r in rules if not r["path_scoped"])

    # Retrieval recommendation heuristic
    typed = {"typescript", "go", "rust", "java", "csharp", "kotlin", "swift", "cpp", "c"}
    typed_share = sum(v for k, v in lang_lines.items() if k in typed) / (sum(lang_lines.values()) or 1)
    if total_code_lines > 300_000 and typed_share < 0.5:
        rec = "claude-context"
    elif typed_share >= 0.5 or "python" in lang_lines:
        rec = "serena"
    else:
        rec = "code-review-graph"

    result = {
        "root": root,
        "files_tracked": len(files),
        "total_bytes": total_bytes,
        "est_total_tokens": total_bytes // 4,
        "total_lines": total_lines,
        "languages": dict(lang_lines.most_common()),
        "top_areas": [{"area": a_, "lines": l, "files": area_files[a_], "share": round(l / total_code_lines, 3)} for a_, l in area_lines.most_common(25)],
        "largest_files": [{"path": r, "bytes": s, "lines": l, "est_tokens": s // 4} for s, l, r in largest[:40]],
        "suggested_deny_rules": deny_unique,
        "review_before_deny": review,
        "generated_files_count": len(generated_files),
        "test_commands": tests,
        "lsp": lsp,
        "tools": tools,
        "existing_settings": settings,
        "claude_md_files": claude_mds,
        "rules_files": rules,
        "always_loaded_instruction_tokens_est": always_loaded,
        "retrieval_recommendation": rec,
        "typed_share": round(typed_share, 2),
    }
    os.makedirs(os.path.dirname(os.path.join(root, a.out)) or ".", exist_ok=True)
    with open(os.path.join(root, a.out), "w") as f:
        json.dump(result, f, indent=2)

    # Compact summary
    print(f"token-diet detect: {len(files)} files, {total_lines:,} lines, ~{total_bytes//4:,} tokens if fully read")
    print("languages: " + ", ".join(f"{k} {v:,}" for k, v in lang_lines.most_common(6)))
    print("top areas: " + ", ".join(f"{t['area']} ({t['share']:.0%})" for t in result["top_areas"][:8]))
    print(f"largest file: {largest[0][2]} (~{largest[0][0]//4:,} tokens)" if largest else "largest file: n/a")
    print(f"CLAUDE.md files: {len(claude_mds)}; always-loaded instructions ≈ {always_loaded:,} tokens")
    print(f"deny-rule candidates: {len(deny_unique)} (+{len(review)} to review); generated files: {len(generated_files)}")
    print("tests: " + (", ".join(sorted({t['cmd'] for t in tests})) or "none detected"))
    print("lsp: " + (", ".join(f"{p} ({'ok' if v['installed'] else 'MISSING ' + v['binary']})" for p, v in lsp.items()) or "none"))
    print("tools: " + ", ".join(k for k, v in tools.items() if v))
    print(f"retrieval recommendation: {rec} (typed share {typed_share:.0%})")
    print(f"full details: {a.out}")


if __name__ == "__main__":
    sys.exit(main())
