// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a4ad1c7122b7
import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { plans } from "./plans";

export const customers = sqliteTable(
  "customers",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    userId: text("user_id").unique(),
    stripeCustomerId: text("stripe_customer_id").unique(),
    stripeSubscriptionId: text("stripe_subscription_id"),
    subscriptionStatus: text("subscription_status", { enum: ["none","incomplete","trialing","active","past_due","paused","canceled","unpaid"] }),
    subscriptionEndsAt: text("subscription_ends_at"),
    cancelAtPeriodEnd: integer("cancel_at_period_end", { mode: "boolean" }),
    planId: text("plan_id").references(() => plans.id, { onDelete: "set null" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check("customers_subscription_status_check", sql`${table.subscriptionStatus} in ('none', 'incomplete', 'trialing', 'active', 'past_due', 'paused', 'canceled', 'unpaid')`),
    index("customers_subscription_status_idx").on(table.subscriptionStatus),
    index("customers_plan_id_idx").on(table.planId),
    index("customers_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
