// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start
import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { companies } from "./companies";
import { contacts } from "./contacts";

export const deals = sqliteTable(
  "deals",
  {
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    amount: real("amount"),
    companyId: text("company_id").references(() => companies.id, { onDelete: "restrict" }).notNull(),
    ownerId: text("owner_id").references(() => contacts.id, { onDelete: "set null" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("deals_company_id_idx").on(table.companyId),
    index("deals_owner_id_idx").on(table.ownerId),
  ],
);
// generated:end
