// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f0e74f5c57aa
import { sql } from "drizzle-orm";
import { check, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const plans = sqliteTable(
  "plans",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    slug: text("slug").notNull().unique(),
    description: text("description"),
    stripeProductId: text("stripe_product_id"),
    stripePriceId: text("stripe_price_id").notNull().unique(),
    amount: integer("amount").notNull(),
    currency: text("currency").notNull(),
    interval: text("interval", { enum: ["month","year"] }),
    active: integer("active", { mode: "boolean" }),
    sort: integer("sort"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check("plans_interval_check", sql`${table.interval} in ('month', 'year')`),
  ],
);
// generated:end
