// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=500c8681dcec
import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { customers } from "./customers";
import { plans } from "./plans";

export const purchases = sqliteTable(
  "purchases",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    customerId: text("customer_id").references(() => customers.id, { onDelete: "restrict" }).notNull(),
    planId: text("plan_id").references(() => plans.id, { onDelete: "set null" }),
    stripeCheckoutSessionId: text("stripe_checkout_session_id").notNull().unique(),
    amount: integer("amount").notNull(),
    currency: text("currency").notNull(),
    status: text("status", { enum: ["pending","paid","failed"] }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("purchases_customer_id_idx").on(table.customerId),
    index("purchases_plan_id_idx").on(table.planId),
    check("purchases_status_check", sql`${table.status} in ('pending', 'paid', 'failed')`),
  ],
);
// generated:end
