// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=ad81e3dfbe17
import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const securityEvents = sqliteTable(
  "security_events",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    kind: text("kind").notNull(),
    severity: text("severity", { enum: ["low","medium","high"] }).notNull(),
    ip: text("ip").notNull(),
    path: text("path").notNull(),
    userAgent: text("user_agent"),
    count: integer("count").notNull(),
    banned: integer("banned", { mode: "boolean" }),
    detail: text("detail"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check("security_events_severity_check", sql`${table.severity} in ('low', 'medium', 'high')`),
    index("security_events_severity_idx").on(table.severity),
    index("security_events_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
