// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1d60d39a0d92
import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const vendors = sqliteTable(
  "vendors",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text("name").notNull(),
    email: text("email").notNull(),
    phone: text("phone"),
    website: text("website"),
    domain: text("domain"),
    country: text("country"),
    brandColor: text("brand_color"),
    handle: text("handle").unique(),
    tier: text("tier", { enum: ["bronze","silver","gold"] }).notNull(),
    services: text("services", { mode: "json" }).$type<("design" | "build" | "hosting" | "support")[]>(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check("vendors_tier_check", sql`${table.tier} in ('bronze', 'silver', 'gold')`),
    index("vendors_tier_idx").on(table.tier),
    index("vendors_created_at_idx").on(table.createdAt),
  ],
);
// generated:end
