// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=15fa9de90c7a
import { createValidators } from "@flaredev/core";
import fileResource from "./file.resource";

export const fileValidators = createValidators(fileResource);
// generated:end
