// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=400f339cdb65
import { createResourceClient } from "@flaredev/core/client";
import type fileResource from "./file.resource";

export const fileClient = createResourceClient<typeof fileResource>("/api/files");

export type File = typeof fileResource.$types.record;
export type FileCreate = typeof fileResource.$types.create;
export type FileUpdate = typeof fileResource.$types.update;
// generated:end
