// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=eb7ce767e8cc
import { createResourceClient } from "@flaredev/core/client";
import type folderResource from "./folder.resource";

export const folderClient = createResourceClient<typeof folderResource>("/api/folders");

export type Folder = typeof folderResource.$types.record;
export type FolderCreate = typeof folderResource.$types.create;
export type FolderUpdate = typeof folderResource.$types.update;
// generated:end
