// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=bb73594c91e5
import { createValidators } from "@flaredev/core";
import folderResource from "./folder.resource";

export const folderValidators = createValidators(folderResource);
// generated:end
