// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=078251fb688e
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import categoryResource from "@/resources/category.resource";

export default function NewCategoryPage() {
  return <ResourceFormPage resource={categoryResource} />;
}
// generated:end
