// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=03d8d14feeb7
import { RecordDetail } from "@/components/dashboard/record-detail";
import planResource from "@/resources/plan.resource";

export default async function PlanDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={planResource} id={(await params).id} />;
}
// generated:end
