// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b5a1c95111aa
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { vendors } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import vendorResource from "@/resources/vendor.resource";

const handlers = createResourceHandlers({
  resource: vendorResource,
  table: vendors,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
