// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f8727abba662
import { createResourceHandlers, drizzleRows } from "@/lib/resource";
import { getDb } from "@/db";
import { vendors } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import vendorResource from "@/resources/vendor.resource";

const handlers = createResourceHandlers({
  resource: vendorResource,
  rows: drizzleRows(vendors, getDb),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
