// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=becc20ec38a6
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import customerResource from "@/resources/customer.resource";

export default async function EditCustomerPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={customerResource} id={(await params).id} />;
}
// generated:end
