// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1499efe7c0a4
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import dealResource from "@/resources/deal.resource";

export default function NewDealPage() {
  return <ResourceFormPage resource={dealResource} />;
}
// generated:end
