// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=601c32da65a4
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { securityEvents } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import securityEventResource from "@/resources/security-event.resource";

const handlers = createResourceHandlers({
  resource: securityEventResource,
  table: securityEvents,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
