// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=2bd351c76fa6
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";

/**
 * Starts a Stripe flow: Checkout (`/api/billing/checkout`) or the portal
 * (`/api/billing/portal`), optionally for one plan. Errors show under the button.
 */
export function BillingButton({
  endpoint,
  planSlug,
  variant = "default",
  children,
}: {
  endpoint: "/api/billing/checkout" | "/api/billing/portal";
  planSlug?: string;
  variant?: "default" | "outline" | "secondary";
  children: React.ReactNode;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function start() {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(planSlug ? { planSlug } : {}),
      });
      const data = (await response.json().catch(() => null)) as { url?: string; error?: string } | null;
      if (!response.ok || !data?.url) {
        setError(data?.error ?? "Stripe could not be reached. Try again in a moment.");
        setBusy(false);
        return;
      }
      window.location.assign(data.url);
    } catch {
      setError("Stripe could not be reached. Try again in a moment.");
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col items-start gap-2">
      <Button onClick={start} disabled={busy} variant={variant}>
        {busy && <Spinner data-icon="inline-start" />}
        {children}
      </Button>
      {error && (
        <p role="alert" className="text-sm text-destructive">
          {error}
        </p>
      )}
    </div>
  );
}
// generated:end
