// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3ccacef73a4a
"use client";

import { BillingButton } from "./billing-button";

/** Opens the Stripe Customer Portal: payment methods, invoices, and cancellation. */
export function BillingPortalButton({ children = "Manage billing" }: { children?: React.ReactNode }) {
  return (
    <BillingButton endpoint="/api/billing/portal" variant="outline">
      {children}
    </BillingButton>
  );
}
// generated:end
