// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d00bd15eaf35
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { contacts } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import contactResource from "@/resources/contact.resource";

const handlers = createResourceHandlers({
  resource: contactResource,
  table: contacts,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end

// Hand-written: lightweight existence check for monitors.
export const HEAD = () => new Response(null, { status: 204, headers: { "x-hand-written": "yes" } });
