// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start
import { createResourceHandlers } from "@flare/core/server";
import { getDb } from "@/db";
import { contacts } from "@/db/schema";
import { authorize } from "@/lib/api";
import contactResource from "@/resources/contact.resource";

const handlers = createResourceHandlers({
  resource: contactResource,
  table: contacts,
  getDb,
  authorize,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
