// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=cb1538cfb896
import { asc, desc, eq } from "drizzle-orm";
import { grantsAccess, isLiveSubscription, type SubscriptionStatus } from "@flaredev/core";
import { getDb } from "@/db";
import { customers, plans, purchases } from "@/db/schema";

export interface BillingSnapshot {
  status: SubscriptionStatus;
  /** Has a subscription that must be changed through the portal, not bought again. */
  live: boolean;
  /** Paid features should be on. */
  access: boolean;
  planId: string | null;
  endsAt: Date | null;
  cancelAtPeriodEnd: boolean;
}

/** The subscription state of a user's Customer row. */
export async function billingSnapshot(userId: string): Promise<BillingSnapshot> {
  const customer = await getDb().select().from(customers).where(eq(customers.userId, userId)).get();
  const status = (customer?.subscriptionStatus ?? "none") as SubscriptionStatus;
  return {
    status,
    live: isLiveSubscription(status),
    access: grantsAccess(status),
    planId: customer?.planId ?? null,
    endsAt: customer?.subscriptionEndsAt ? new Date(customer.subscriptionEndsAt) : null,
    cancelAtPeriodEnd: customer?.cancelAtPeriodEnd ?? false,
  };
}

/** Active plans, cheapest first: subscriptions (with an interval) and one-time products. */
export async function availablePlans() {
  const rows = await getDb()
    .select({ id: plans.id, name: plans.name, slug: plans.slug, description: plans.description, amount: plans.amount, currency: plans.currency, interval: plans.interval, active: plans.active })
    .from(plans)
    .orderBy(asc(plans.sort), asc(plans.amount));
  const active = rows.filter((plan) => plan.active !== false);
  return { subscriptions: active.filter((plan) => plan.interval), oneTime: active.filter((plan) => !plan.interval) };
}

/** A user's one-time purchases, newest first. */
export async function userPurchases(userId: string) {
  const customer = await getDb().select({ id: customers.id }).from(customers).where(eq(customers.userId, userId)).get();
  if (!customer) return [];
  return getDb()
    .select({ id: purchases.id, status: purchases.status, amount: purchases.amount, currency: purchases.currency, createdAt: purchases.createdAt, plan: plans.name })
    .from(purchases)
    .leftJoin(plans, eq(purchases.planId, plans.id))
    .where(eq(purchases.customerId, customer.id))
    .orderBy(desc(purchases.createdAt));
}
// generated:end
