// Generated by `flare gen security`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c294ef13df94
import { env as runtimeEnv } from "cloudflare:workers";
import { createZoneClient } from "@flare/core/security";
import { createSecurity, type BanStore, type MonitorNamespace, type RateLimiter, type Security } from "@flare/core/security/server";
import { getDb } from "../db";
import { securityEvents } from "../db/schema";
import config from "../security.config";

/** Minimal ExecutionContext surface worker/index.ts passes in. */
export interface SecurityContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface SecurityEnv {
  FLARE_SECURITY: BanStore;
  FLARE_SECURITY_MONITOR: MonitorNamespace;
  FLARE_RATE_LIMIT?: RateLimiter;
  /** With both set (wrangler secrets), bans also become zone IP Access Rules. */
  FLARE_SECURITY_ZONE_ID?: string;
  FLARE_SECURITY_API_TOKEN?: string;
}

/** This app's tag on zone rules, so Flare only ever changes its own. */
const APP = "demo";

const bindings = () => runtimeEnv as unknown as SecurityEnv;
let instance: Security | undefined;

/** The app's security layer, one per isolate. */
export function security(): Security {
  const env = bindings();
  instance ??= createSecurity({
    config,
    bans: env.FLARE_SECURITY,
    monitors: env.FLARE_SECURITY_MONITOR,
    rateLimiter: env.FLARE_RATE_LIMIT,
    zone: zoneClient(),
    // Every tripped detector becomes a SecurityEvent row.
    onTrip: (trip) =>
      logSecurityEvent({
        kind: trip.detector.name,
        severity: trip.detector.severity ?? "medium",
        ip: trip.ip,
        path: trip.path,
        userAgent: trip.userAgent,
        count: trip.count,
        banned: trip.banned,
        detail: trip.detector.description ?? null,
      }),
  });
  return instance;
}

/** The zone layer, when this app has a zone and a scoped API token configured. */
export function zoneClient() {
  const env = bindings();
  return env.FLARE_SECURITY_ZONE_ID && env.FLARE_SECURITY_API_TOKEN
    ? createZoneClient({ zoneId: env.FLARE_SECURITY_ZONE_ID, apiToken: env.FLARE_SECURITY_API_TOKEN, app: APP })
    : null;
}

export async function logSecurityEvent(event: typeof securityEvents.$inferInsert): Promise<void> {
  await getDb().insert(securityEvents).values(event);
}

/** Called by worker/index.ts for every request. */
export function protect(request: Request, _env: unknown, ctx: SecurityContext, next: () => Promise<Response>): Promise<Response> {
  return security().protect(request, ctx, next);
}
// generated:end
