// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=2fac36dcf6dc
import Stripe from "stripe";
import { env } from "cloudflare:workers";
import { and, eq, isNull } from "drizzle-orm";
import { checkoutPaid, shouldApplySubscription, subscriptionState } from "@flare/core";
import { getDb } from "@/db";
import { customers, plans, purchases } from "@/db/schema";

export type CustomerRow = typeof customers.$inferSelect;

/** This app's tag in Stripe metadata (flare_app), so several apps can share one Stripe account. */
const FLARE_APP = "demo";

export function stripeSecrets(): { STRIPE_SECRET_KEY?: string; STRIPE_WEBHOOK_SECRET?: string; BETTER_AUTH_URL?: string } {
  return env as { STRIPE_SECRET_KEY?: string; STRIPE_WEBHOOK_SECRET?: string; BETTER_AUTH_URL?: string };
}

/** The Stripe client. Throws a clear error when STRIPE_SECRET_KEY is unset. */
export function createStripe(): Stripe {
  const { STRIPE_SECRET_KEY } = stripeSecrets();
  if (!STRIPE_SECRET_KEY) {
    throw new Error("STRIPE_SECRET_KEY is not set. Add it to .dev.vars locally and run `wrangler secret put STRIPE_SECRET_KEY` for production.");
  }
  return new Stripe(STRIPE_SECRET_KEY, { apiVersion: "2026-08-26.dahlia", httpClient: Stripe.createFetchHttpClient() });
}

/**
 * The app's own origin for Checkout and portal return URLs. Comes from
 * BETTER_AUTH_URL when set, else the request URL, never from forwarded headers
 * a client could spoof to send users elsewhere after paying.
 */
export function appOrigin(request: Request): string {
  const configured = stripeSecrets().BETTER_AUTH_URL;
  return (configured ? new URL(configured) : new URL(request.url)).origin;
}

/**
 * The Customer row that pays for a signed-in user, with a Stripe customer attached.
 * Creates both on first use, links a row an admin created for the same email, and
 * backfills a row that has no Stripe customer yet. The idempotency key makes a
 * double click create one Stripe customer, not two.
 */
export async function getOrCreateCustomer(user: { id: string; email: string; name: string | null }): Promise<CustomerRow & { stripeCustomerId: string }> {
  const db = getDb();
  let row: CustomerRow | undefined =
    (await db.select().from(customers).where(eq(customers.userId, user.id)).get()) ??
    (await db
      .update(customers)
      .set({ userId: user.id })
      .where(and(eq(customers.email, user.email), isNull(customers.userId)))
      .returning()
      .get());
  if (!row) {
    row = await db
      .insert(customers)
      .values({ id: crypto.randomUUID(), name: user.name ?? user.email, email: user.email, userId: user.id, subscriptionStatus: "none", createdAt: new Date(), updatedAt: new Date() })
      .onConflictDoNothing()
      .returning()
      .get();
    row ??= await db.select().from(customers).where(eq(customers.userId, user.id)).get();
    if (!row) throw new Error("Could not create the customer record.");
  }
  if (row.stripeCustomerId) return row as CustomerRow & { stripeCustomerId: string };

  const stripeCustomer = await createStripe().customers.create(
    { email: user.email, name: user.name ?? undefined, metadata: { flareCustomerId: row.id } },
    { idempotencyKey: `flare-customer-${row.id}` },
  );
  const linked = await db.update(customers).set({ stripeCustomerId: stripeCustomer.id, updatedAt: new Date() }).where(eq(customers.id, row.id)).returning().get();
  return linked as CustomerRow & { stripeCustomerId: string };
}

let portalConfiguration: string | undefined;

/**
 * The portal configuration `flare billing:sync-plans` maintains for this app (metadata flare_app),
 * which allows switching between the synced plans. Undefined falls back to the
 * account's default portal settings.
 */
export async function billingPortalConfiguration(stripe: Stripe): Promise<string | undefined> {
  if (portalConfiguration) return portalConfiguration;
  for await (const configuration of stripe.billingPortal.configurations.list({ active: true, limit: 100 })) {
    if (configuration.metadata?.flare_app === FLARE_APP) return (portalConfiguration = configuration.id);
  }
  return undefined;
}

function idOf(value: string | { id: string } | null | undefined): string | null {
  if (!value) return null;
  return typeof value === "string" ? value : value.id;
}

/**
 * Write a subscription's CURRENT state to its Customer. Every event re-fetches the
 * subscription from Stripe instead of trusting the event payload, so duplicate and
 * out-of-order deliveries all converge on the same, latest state.
 */
export async function syncSubscription(subscriptionId: string): Promise<void> {
  const subscription = await createStripe().subscriptions.retrieve(subscriptionId);
  const db = getDb();
  const customer = await db.select().from(customers).where(eq(customers.stripeCustomerId, idOf(subscription.customer) ?? "")).get();
  if (!customer) return;
  if (!shouldApplySubscription(customer, subscription)) return;

  const state = subscriptionState(subscription);
  const plan = state.priceId ? await db.select({ id: plans.id }).from(plans).where(eq(plans.stripePriceId, state.priceId)).get() : undefined;
  await db
    .update(customers)
    .set({
      stripeSubscriptionId: state.stripeSubscriptionId,
      subscriptionStatus: state.subscriptionStatus,
      // datetime fields are stored as ISO text.
      subscriptionEndsAt: state.subscriptionEndsAt?.toISOString() ?? null,
      cancelAtPeriodEnd: state.cancelAtPeriodEnd,
      planId: plan?.id ?? null,
      updatedAt: new Date(),
    })
    .where(eq(customers.id, customer.id));
}

/**
 * A Checkout Session finished. Subscriptions sync from Stripe; one-time payments
 * record a Purchase, marked paid only once the money has settled.
 */
export async function syncCheckoutSession(sessionId: string): Promise<void> {
  const session = await createStripe().checkout.sessions.retrieve(sessionId, { expand: ["line_items"] });
  if (session.mode === "subscription") {
    const subscriptionId = idOf(session.subscription);
    if (subscriptionId) await syncSubscription(subscriptionId);
    return;
  }
  if (session.mode !== "payment") return;

  const db = getDb();
  const customer = await db.select().from(customers).where(eq(customers.stripeCustomerId, idOf(session.customer) ?? "")).get();
  if (!customer) return;
  const priceId = session.line_items?.data?.[0]?.price?.id ?? null;
  const plan = priceId ? await db.select({ id: plans.id }).from(plans).where(eq(plans.stripePriceId, priceId)).get() : undefined;
  const status = checkoutPaid(session) ? "paid" : session.status === "expired" ? "failed" : "pending";
  await db
    .insert(purchases)
    .values({
      id: crypto.randomUUID(),
      customerId: customer.id,
      planId: plan?.id ?? null,
      stripeCheckoutSessionId: session.id,
      amount: session.amount_total ?? 0,
      currency: session.currency ?? "usd",
      status,
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({ target: purchases.stripeCheckoutSessionId, set: { status, updatedAt: new Date() } });
}

/** A delayed one-time payment failed after the session completed. */
export async function failCheckoutSession(sessionId: string): Promise<void> {
  await getDb().update(purchases).set({ status: "failed", updatedAt: new Date() }).where(eq(purchases.stripeCheckoutSessionId, sessionId));
}

/** The subscription an invoice belongs to (its location moved in API 2025-03-31). */
export function invoiceSubscriptionId(invoice: Stripe.Invoice): string | null {
  const legacy = (invoice as unknown as { subscription?: string | { id: string } | null }).subscription;
  return idOf(invoice.parent?.subscription_details?.subscription ?? legacy ?? null);
}
// generated:end
