// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=49c83f059353
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { deals } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import dealResource from "@/resources/deal.resource";

const handlers = createResourceHandlers({
  resource: dealResource,
  table: deals,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
