// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f5c0d5fef13f
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import contactResource from "@/resources/contact.resource";

export default async function EditContactPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={contactResource} id={(await params).id} />;
}
// generated:end
