// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=be44693ec9e1
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { securityEvents } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import securityEventResource from "@/resources/security-event.resource";

const handlers = createResourceHandlers({
  resource: securityEventResource,
  table: securityEvents,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
