import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { planRows, renderSyncSql, type StripePrice } from "../src/commands/billing-sync.js";
import { genBilling } from "../src/commands/gen-billing.js";
import { genResource } from "../src/commands/gen.js";
import { validateBillingOptions } from "../src/generator/billing.js";

const scratch = mkdtempSync(join(import.meta.dirname, ".tmp-billing-"));
afterAll(() => rmSync(scratch, { recursive: true, force: true }));

const quiet = { log: () => {}, skipInstall: true, skipMigration: true };
const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");

function app() {
  const root = join(scratch, `app-${Math.random().toString(36).slice(2)}`);
  mkdirSync(root, { recursive: true });
  writeFileSync(join(root, "package.json"), JSON.stringify({ dependencies: { vinext: "1" } }));
  writeFileSync(join(root, ".dev.vars"), "BETTER_AUTH_SECRET=x\n");
  return root;
}

describe("flare gen billing", () => {
  it("scaffolds the resources, admin-only write policies, routes and page", async () => {
    const root = app();
    await genBilling({ ...quiet, cwd: root });

    for (const name of ["plan", "customer", "purchase"]) expect(existsSync(join(root, `resources/${name}.resource.ts`)), name).toBe(true);
    expect(read(root, "resources/customer.resource.ts")).toContain("subscriptionStatus: field.enum(");
    expect(read(root, "resources/customer.resource.ts")).toContain("cancelAtPeriodEnd");

    // Subscription status grants access, so nobody may write it through the API.
    const customerPolicy = read(root, "policies/customer.policy.ts");
    expect(customerPolicy).toContain(`read: ["admin", "staff"]`);
    expect(customerPolicy).toContain(`update: ["admin"]`);
    expect(read(root, "policies/plan.policy.ts")).toContain(`read: ["*"]`);
    expect(read(root, "policies/index.ts")).toMatch(/Customer: customerPolicy[\s\S]*Plan: planPolicy[\s\S]*Purchase: purchasePolicy/);

    for (const path of [
      "lib/stripe.ts",
      "lib/billing.ts",
      "app/api/billing/checkout/route.ts",
      "app/api/billing/portal/route.ts",
      "app/api/webhooks/stripe/route.ts",
      "components/billing/billing-button.tsx",
      "components/billing/billing-portal-button.tsx",
      "app/dashboard/billing/page.tsx",
    ]) {
      expect(read(root, path), path).toMatch(/Generated by `flare gen billing`[\s\S]*generated:start hash=/);
    }
    const webhook = read(root, "app/api/webhooks/stripe/route.ts");
    expect(webhook).toContain("constructEventAsync");
    expect(webhook).toContain("createSubtleCryptoProvider");
    expect(webhook).not.toContain(".constructEvent(");

    expect(read(root, "package.json")).toContain(`"stripe"`);
    expect(read(root, ".dev.vars")).toContain("STRIPE_WEBHOOK_SECRET=");
  });

  it("is idempotent", async () => {
    const root = app();
    await genBilling({ ...quiet, cwd: root });
    const again = await genBilling({ ...quiet, cwd: root });
    expect(again.files.every((file) => file.outcome === "identical")).toBe(true);
    expect(read(root, ".dev.vars").match(/STRIPE_SECRET_KEY/g)).toHaveLength(1);
  });

  it("adds the subscription fields to an existing Customer, keeping its own fields", async () => {
    const root = app();
    await genResource("Customer", { log: () => {}, skipMigration: true, cwd: root, fields: "name:string, email:string!, loyaltyTier:enum(bronze,gold)?" });
    await genBilling({ ...quiet, cwd: root });
    const descriptor = read(root, "resources/customer.resource.ts");
    expect(descriptor).toContain("loyaltyTier");
    expect(descriptor).toContain("stripeCustomerId");
    expect(descriptor).toContain("subscriptionStatus");
    expect(descriptor.match(/email:/g)).toHaveLength(1);
  });

  it("refuses to merge into a hand-edited fields block unless --force", async () => {
    const root = app();
    await genResource("Customer", { log: () => {}, skipMigration: true, cwd: root, fields: "name:string, email:string!" });
    const path = join(root, "resources/customer.resource.ts");
    writeFileSync(path, readFileSync(path, "utf8").replace("name: field.string()", "name: field.string({ maxLength: 80 })"));
    await expect(genBilling({ ...quiet, cwd: root })).rejects.toThrow(/edited by hand[\s\S]*--force/);
    await genBilling({ ...quiet, cwd: root, force: true });
    expect(read(root, "resources/customer.resource.ts")).toContain("stripeCustomerId");
  });

  it("supports only the stripe provider and the subscriptions mode", () => {
    expect(() => validateBillingOptions("paddle", undefined)).toThrow(/not supported/);
    expect(() => validateBillingOptions("stripe", "checkout")).toThrow(/not supported/);
    expect(() => validateBillingOptions("stripe", "subscriptions")).not.toThrow();
  });
});

const price = (id: string, overrides: Partial<StripePrice> = {}): StripePrice => ({
  id,
  type: "recurring",
  unit_amount: 1000,
  currency: "usd",
  recurring: { interval: "month" },
  ...overrides,
});

describe("billing:sync-plans", () => {
  it("makes one row per usable price, with distinct slugs", () => {
    const { rows, skipped } = planRows([
      { product: { id: "prod_starter", name: "Starter" }, prices: [price("p1")] },
      {
        product: { id: "prod_pro", name: "Pro", metadata: { slug: "pro", sort: "2" } },
        prices: [price("p2"), price("p3", { unit_amount: 10_000, recurring: { interval: "year" } }), price("p4", { recurring: { interval: "week" } })],
      },
      { product: { id: "prod_pack", name: "Credit pack" }, prices: [price("p5", { type: "one_time", recurring: null, unit_amount: 500 })] },
      { product: { id: "prod_intl", name: "Team" }, prices: [price("p6"), price("p7", { currency: "eur" })] },
    ]);

    expect(rows.map((row) => row.slug)).toEqual(["starter", "pro-month", "pro-year", "credit-pack", "team-month-usd", "team-month-eur"]);
    expect(rows.find((row) => row.slug === "credit-pack")).toMatchObject({ interval: null, amount: 500 });
    expect(rows.find((row) => row.slug === "pro-year")).toMatchObject({ name: "Pro (yearly)", sort: 2 });
    expect(skipped).toEqual(["Pro (p4)"]);
  });

  it("upserts by price, escapes text, and deactivates prices no longer in Stripe", () => {
    const sql = renderSyncSql(
      [{ name: "Owner's plan", slug: "owners", description: null, stripeProductId: "prod_1", stripePriceId: "price_1", amount: 1200, currency: "usd", interval: "month", sort: 0 }],
      () => "id-1",
    );
    expect(sql).toContain(`'Owner''s plan'`);
    expect(sql).toContain("ON CONFLICT(stripe_price_id) DO UPDATE");
    expect(sql).toContain("UPDATE plans SET active = 0 WHERE stripe_price_id IS NOT NULL AND stripe_price_id NOT IN ('price_1');");
    expect(renderSyncSql([])).toContain("UPDATE plans SET active = 0 WHERE stripe_price_id IS NOT NULL;");
  });
});
