import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "jsonc-parser";
import { afterAll, describe, expect, it } from "vitest";
import { loadSecurityConfig, provisionZoneSecurity } from "../src/commands/deploy.js";
import { genSecurity } from "../src/commands/gen-security.js";
import { addSecurityBindings } from "../src/generator/security.js";

const scratch = mkdtempSync(join(import.meta.dirname, ".tmp-security-"));
afterAll(() => rmSync(scratch, { recursive: true, force: true }));

const quiet = { log: () => {}, skipMigration: true };
const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");
const template = join(import.meta.dirname, "../templates/app");

const WRANGLER = `{
  "name": "shop",
  // Realtime rooms.
  "durable_objects": { "bindings": [{ "name": "FLARE_REALTIME", "class_name": "RealtimeChannel" }] },
  "migrations": [{ "tag": "v1", "new_sqlite_classes": ["RealtimeChannel"] }],
  "kv_namespaces": [{ "binding": "VINEXT_KV_CACHE" }]
}
`;

function app() {
  const root = join(scratch, `app-${Math.random().toString(36).slice(2)}`);
  mkdirSync(join(root, "lib"), { recursive: true });
  writeFileSync(join(root, "package.json"), JSON.stringify({ name: "shop", dependencies: { vinext: "1" } }));
  writeFileSync(join(root, "wrangler.jsonc"), WRANGLER);
  for (const file of ["lib/security.ts", "lib/dashboard-nav.ts"]) copyFileSync(join(template, file), join(root, file));
  return root;
}

describe("addSecurityBindings", () => {
  it("adds the KV, Durable Object, migration and rate-limit bindings, keeping comments and existing ones", () => {
    const { text, added } = addSecurityBindings(WRANGLER);
    expect(added).toHaveLength(4);
    expect(text).toContain("// Realtime rooms.");
    const config = parse(text);
    expect(config.kv_namespaces.map((kv: { binding: string }) => kv.binding)).toEqual(["VINEXT_KV_CACHE", "FLARE_SECURITY"]);
    expect(config.durable_objects.bindings.map((binding: { name: string }) => binding.name)).toEqual(["FLARE_REALTIME", "FLARE_SECURITY_MONITOR"]);
    expect(config.migrations.at(-1)).toEqual({ tag: "flare-security-v1", new_sqlite_classes: ["SecurityMonitor"] });
    expect(config.ratelimits[0]).toMatchObject({ name: "FLARE_RATE_LIMIT", simple: { limit: 120, period: 60 } });
  });

  it("is idempotent and works on a config without those sections", () => {
    const first = addSecurityBindings(`{ "name": "x" }`);
    expect(parse(first.text).durable_objects.bindings[0].class_name).toBe("SecurityMonitor");
    expect(addSecurityBindings(first.text)).toEqual({ text: first.text, added: [] });
  });
});

describe("flare gen security", () => {
  it("scaffolds config, resource, policy, guard, dashboard, sidebar link and bindings", async () => {
    const root = app();
    const result = await genSecurity({ ...quiet, cwd: root });

    expect(read(root, "security.config.ts")).toContain("DEFAULT_DETECTORS");
    const descriptor = read(root, "resources/security-event.resource.ts");
    for (const field of ["kind", "severity", "ip", "path", "userAgent", "count", "banned", "detail"]) expect(descriptor).toContain(`${field}:`);
    const policy = read(root, "policies/security-event.policy.ts");
    expect(policy).toContain(`read: ["admin", "staff"]`);
    expect(policy).toContain(`create: ["admin"]`);

    const guard = read(root, "lib/security.ts");
    expect(guard).toMatch(/^\/\/ Generated by `flare gen security`/);
    expect(guard).not.toContain("Security is off");
    expect(guard).toContain("createSecurity(");
    expect(guard).toContain(`const APP = "shop"`);
    expect(guard).toContain("export function protect(");

    expect(read(root, "app/dashboard/security/page.tsx")).toContain("security().bans()");
    expect(read(root, "app/dashboard/security/actions.ts")).toMatch(/^\/\/ Generated[\s\S]*"use server"/);
    expect(read(root, "lib/dashboard-nav.ts")).toContain(`href: "/dashboard/security"`);
    // The hand-written part after the block stays.
    // The app's own links sit around the generated block; a generator adds to the block.
    const nav = read(root, "lib/dashboard-nav.ts");
    expect(nav).toContain(`{ label: "Costs", href: "/dashboard/costs", icon: "wallet" }`);
    expect(nav).toContain(`...generatedDashboardLinks,`);
    expect(nav).toContain(`{ label: "API reference", href: "/api/reference", icon: "book" },`);
    expect(result.bindings).toHaveLength(4);
    expect(existsSync(join(root, "db/schema/security-events.ts")) || existsSync(join(root, "db/schema/securityEvents.ts")) || read(root, "db/schema.ts").includes("security")).toBe(true);
  });

  it("is idempotent", async () => {
    const root = app();
    await genSecurity({ ...quiet, cwd: root });
    const again = await genSecurity({ ...quiet, cwd: root });
    expect(again.files.every((file) => file.outcome === "identical")).toBe(true);
    expect(again.bindings).toEqual([]);
  });

  it("loads the generated security.config.ts for deploy", async () => {
    const root = app();
    await genSecurity({ ...quiet, cwd: root });
    const config = await loadSecurityConfig(root);
    expect(config?.detectors?.map((detector) => detector.name)).toContain("login-brute-force");
    expect(config?.zone?.rateLimits?.[0]?.name).toBe("sign-in");
    expect(await loadSecurityConfig(scratch)).toBeNull();
  });
});

describe("provisionZoneSecurity", () => {
  it("replaces only this app's rules in each phase", async () => {
    const root = app();
    const calls: { method: string; url: string; body?: unknown }[] = [];
    const existing = [
      { id: "1", action: "block", expression: "true", description: "someone else's rule" },
      { id: "2", action: "block", expression: "old", description: "flare:shop:sign-in" },
    ];
    const fakeFetch = (async (url: string, init?: RequestInit) => {
      calls.push({ method: init?.method ?? "GET", url, body: init?.body ? JSON.parse(String(init.body)) : undefined });
      return Response.json({ success: true, result: { rules: existing } });
    }) as typeof fetch;

    await provisionZoneSecurity(
      root,
      {
        zone: {
          rateLimits: [{ name: "sign-in", expression: 'http.request.uri.path eq "/login"', requests: 10, periodSeconds: 10, mitigationSeconds: 10 }],
          customRules: [{ name: "scanners", expression: 'http.request.uri.path contains "/.env"', action: "block" }],
        },
      },
      { zoneId: "z1", apiToken: "t" },
      { log: () => {}, fetch: fakeFetch },
    );

    const puts = calls.filter((call) => call.method === "PUT");
    expect(puts.map((call) => call.url)).toEqual([
      "https://api.cloudflare.com/client/v4/zones/z1/rulesets/phases/http_ratelimit/entrypoint",
      "https://api.cloudflare.com/client/v4/zones/z1/rulesets/phases/http_request_firewall_custom/entrypoint",
    ]);
    const rateRules = (puts[0]!.body as { rules: { description: string }[] }).rules.map((rule) => rule.description);
    expect(rateRules).toEqual(["someone else's rule", "flare:shop:sign-in"]);
    const customRules = (puts[1]!.body as { rules: { description: string }[] }).rules.map((rule) => rule.description);
    expect(customRules).toEqual(["someone else's rule", "flare:shop:scanners"]);
  });
});
