// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=83943908f2ef
import { createResourceHandlers, drizzleRows } from "@/lib/resource";
import { getDb } from "@/db";
import { vendors } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import vendorResource from "@/resources/vendor.resource";

const handlers = createResourceHandlers({
  resource: vendorResource,
  rows: drizzleRows(vendors, getDb),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
