// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=4c7589a5828a
import { FormSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton actions={0} />
      <FormSkeleton fields={1} />
    </>
  );
}
// generated:end
