// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=29706d8ba766
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import companyResource from "@/resources/company.resource";

export default async function EditCompanyPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={companyResource} id={(await params).id} />;
}
// generated:end
