// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=4fdbc39b4f60
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { orderItems } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import orderItemResource from "@/resources/order-item.resource";

const handlers = createResourceHandlers({
  resource: orderItemResource,
  table: orderItems,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
