// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=02cb52102976
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import planResource from "@/resources/plan.resource";

export const metadata = { title: planResource.pluralLabel };

export default async function PlanListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={planResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: planResource.pluralLabel }]}
      />
      <ResourceStats resource={planResource} />
      <ResourceChart resource={planResource} />
      <ResourceTable resource={planResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
