// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=73ac3ace648f
import { createResourceHandlers } from "@flaredev/core/server";
import { prismaRows } from "@flaredev/core/server";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import categoryResource from "@/resources/category.resource";

const handlers = createResourceHandlers({
  resource: categoryResource,
  rows: prismaRows(prisma.category, prisma),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
