// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1353e90736f4
import { createValidators } from "@flaredev/core";
import categoryResource from "./category.resource";

export const categoryValidators = createValidators(categoryResource);
// generated:end
