// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f207cd85ed75
import { createValidators } from "@flaredev/core";
import orderResource from "./order.resource";

export const orderValidators = createValidators(orderResource);
// generated:end
