// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a5a05529f7eb
import { createValidators } from "@flaredev/core";
import productResource from "./product.resource";

export const productValidators = createValidators(productResource);
// generated:end
