// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d08bd6431b2c
import { createResourceClient } from "@flaredev/core/client";
import type productResource from "./product.resource";

export const productClient = createResourceClient<typeof productResource>("/api/products");

export type Product = typeof productResource.$types.record;
export type ProductCreate = typeof productResource.$types.create;
export type ProductUpdate = typeof productResource.$types.update;
// generated:end
