// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1e5a71b3df33
import { createResourceStore, prismaRows, crossOrigin, drain, failureResponse, problem, readJson, respond, type RouteContext } from "@/lib/resource";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import orderResource from "@/resources/order.resource";

const store = createResourceStore({
  resource: orderResource,
  rows: prismaRows(prisma.order, prisma),
  currentUser,
  onChange: revalidateResource,
});

/** GET /api/orders/[id] — read one order. */
export async function GET(request: Request, context: RouteContext): Promise<Response> {
  const { id } = await context.params;
  const denied = await authorize({ request, resource: orderResource, action: "read", id });
  if (denied) return denied;

  return respond(await store.get(id));
}

/** PATCH /api/orders/[id] — change some fields of one order. */
export async function PATCH(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: orderResource, action: "update", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    return respond(await store.update(id, read.body));
  } finally {
    await drain(request);
  }
}

/** PUT /api/orders/[id] — replace one order entirely. */
export async function PUT(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: orderResource, action: "update", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    return respond(await store.replace(id, read.body));
  } finally {
    await drain(request);
  }
}

/** DELETE /api/orders/[id] — remove one order. */
export async function DELETE(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: orderResource, action: "delete", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const result = await store.delete(id);
    return result.ok ? new Response(null, { status: 204 }) : failureResponse(result);
  } finally {
    await drain(request);
  }
}
// generated:end
