// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=8b772dff050e
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import dealResource from "@/resources/deal.resource";

export const metadata = { title: dealResource.pluralLabel };

export default async function DealListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={dealResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: dealResource.pluralLabel }]}
      />
      <ResourceStats resource={dealResource} />
      <ResourceTable resource={dealResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
