// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1bcd6b8c2ea2
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import planResource from "@/resources/plan.resource";

export default function NewPlanPage() {
  return <ResourceFormPage resource={planResource} />;
}
// generated:end
