// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=62043fc7e405
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { products } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import productResource from "@/resources/product.resource";

const handlers = createResourceHandlers({
  resource: productResource,
  table: products,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
