// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=73d4c5942a1b
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { customers } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import customerResource from "@/resources/customer.resource";

const handlers = createResourceHandlers({
  resource: customerResource,
  table: customers,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
