// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=93b78766373b
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import folderResource from "@/resources/folder.resource";

export const metadata = { title: folderResource.pluralLabel };

export default async function FolderListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={folderResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: folderResource.pluralLabel }]}
      />
      <ResourceStats resource={folderResource} />
      <ResourceChart resource={folderResource} />
      <ResourceTable resource={folderResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
