// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=90e9e871b3ee
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import companyResource from "@/resources/company.resource";

export default function NewCompanyPage() {
  return <ResourceFormPage resource={companyResource} />;
}
// generated:end
