// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=6ed1854bc0b0
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import orderResource from "@/resources/order.resource";

export const metadata = { title: orderResource.pluralLabel };

export default async function OrderListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={orderResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: orderResource.pluralLabel }]}
      />
      <ResourceStats resource={orderResource} />
      <ResourceChart resource={orderResource} />
      <ResourceTable resource={orderResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
