// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c87662b59366
import { createResourceHandlers, drizzleRows } from "@/lib/resource";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import planResource from "@/resources/plan.resource";

const handlers = createResourceHandlers({
  resource: planResource,
  rows: drizzleRows(plans, getDb),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
