// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=48aaccf529ba
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { BillingButton } from "@/components/billing/billing-button";
import { BillingPortalButton } from "@/components/billing/billing-portal-button";
import { requireSession } from "@/lib/session";
import { availablePlans, billingSnapshot, userPurchases } from "@/lib/billing";

const STATUS: Record<string, { label: string; tone: "secondary" | "success" | "warning" | "danger" }> = {
  none: { label: "No subscription", tone: "secondary" },
  incomplete: { label: "Payment pending", tone: "warning" },
  trialing: { label: "Trial", tone: "success" },
  active: { label: "Active", tone: "success" },
  past_due: { label: "Payment failed, retrying", tone: "warning" },
  paused: { label: "Paused", tone: "secondary" },
  canceled: { label: "Canceled", tone: "secondary" },
  unpaid: { label: "Unpaid", tone: "danger" },
};

const money = (cents: number, currency: string) =>
  new Intl.NumberFormat(undefined, { style: "currency", currency: currency.toUpperCase() }).format(cents / 100);
const day = (date: Date) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(date);

export default async function BillingPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requireSession("/dashboard/billing");
  const [billing, { subscriptions, oneTime }, purchases, params] = await Promise.all([
    billingSnapshot(session.user.id),
    availablePlans(),
    userPurchases(session.user.id),
    searchParams,
  ]);
  const status = STATUS[billing.status] ?? STATUS.none!;
  const current = subscriptions.find((plan) => billing.live && plan.id === billing.planId);

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-col gap-8 px-4 py-10">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold">Billing</h1>
          <p className="text-sm text-muted-foreground">
            {current
              ? billing.cancelAtPeriodEnd && billing.endsAt
                ? `${current.name} ends on ${day(billing.endsAt)}.`
                : billing.endsAt
                  ? `${current.name} renews on ${day(billing.endsAt)}.`
                  : `You're on ${current.name}.`
              : "Choose a plan to get started."}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Badge variant={status.tone}>{status.label}</Badge>
          {billing.live && <BillingPortalButton />}
        </div>
      </div>

      {params.checkout === "success" && (
        <Alert>
          <AlertDescription>Payment received. Your plan updates here as soon as Stripe confirms it, usually within seconds.</AlertDescription>
        </Alert>
      )}

      {subscriptions.length > 0 && (
        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-medium">Plans</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {subscriptions.map((plan) => {
              const isCurrent = plan.id === current?.id;
              return (
                <Card key={plan.id} className={isCurrent ? "border-primary" : undefined}>
                  <CardHeader>
                    <CardTitle>{plan.name}</CardTitle>
                    <CardDescription>
                      {money(plan.amount, plan.currency)} per {plan.interval}
                    </CardDescription>
                  </CardHeader>
                  {plan.description && <CardContent className="text-sm text-muted-foreground">{plan.description}</CardContent>}
                  <CardFooter>
                    {isCurrent ? (
                      <span className="text-sm text-muted-foreground">Your current plan</span>
                    ) : billing.live ? (
                      <BillingButton endpoint="/api/billing/portal" planSlug={plan.slug} variant="outline">
                        Switch to {plan.name}
                      </BillingButton>
                    ) : (
                      <BillingButton endpoint="/api/billing/checkout" planSlug={plan.slug}>
                        Subscribe
                      </BillingButton>
                    )}
                  </CardFooter>
                </Card>
              );
            })}
          </div>
        </section>
      )}

      {oneTime.length > 0 && (
        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-medium">Buy once</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {oneTime.map((plan) => (
              <Card key={plan.id}>
                <CardHeader>
                  <CardTitle>{plan.name}</CardTitle>
                  <CardDescription>{money(plan.amount, plan.currency)}, one-time</CardDescription>
                </CardHeader>
                {plan.description && <CardContent className="text-sm text-muted-foreground">{plan.description}</CardContent>}
                <CardFooter>
                  <BillingButton endpoint="/api/billing/checkout" planSlug={plan.slug} variant="outline">
                    Buy {plan.name}
                  </BillingButton>
                </CardFooter>
              </Card>
            ))}
          </div>
        </section>
      )}

      {subscriptions.length === 0 && oneTime.length === 0 && (
        <p className="text-sm text-muted-foreground">
          No plans yet. Create products in Stripe, then run <code>flare billing:sync-plans</code>.
        </p>
      )}

      {purchases.length > 0 && (
        <section className="flex flex-col gap-2">
          <h2 className="text-sm font-medium">Purchases</h2>
          <ul className="flex flex-col divide-y rounded-lg border text-sm">
            {purchases.map((purchase) => (
              <li key={purchase.id} className="flex items-center justify-between gap-4 px-4 py-3">
                <span className="truncate">{purchase.plan ?? "One-time purchase"}</span>
                <span className="flex items-center gap-3 tabular-nums text-muted-foreground">
                  {money(purchase.amount, purchase.currency)}
                  <Badge variant={purchase.status === "paid" ? "success" : purchase.status === "failed" ? "danger" : "warning"}>
                    {purchase.status === "paid" ? "Paid" : purchase.status === "failed" ? "Failed" : "Pending"}
                  </Badge>
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <Link href="/dashboard" className="text-sm text-muted-foreground underline underline-offset-4">
        Back to the dashboard
      </Link>
    </main>
  );
}
// generated:end
