// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=7dc1a4ac502f
import { RecordDetail } from "@/components/dashboard/record-detail";
import vendorResource from "@/resources/vendor.resource";

export default async function VendorDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={vendorResource} id={(await params).id} />;
}
// generated:end
