// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b45ebb8f5e95
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import fileResource from "@/resources/file.resource";

export default function NewFilePage() {
  return <ResourceFormPage resource={fileResource} />;
}
// generated:end
