// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=406ae8216a31
import { DetailSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton />
      <DetailSkeleton rows={5} />
    </>
  );
}
// generated:end
