// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c372f1928cf6
import { RecordDetail } from "@/components/dashboard/record-detail";
import fileResource from "@/resources/file.resource";

export default async function FileDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={fileResource} id={(await params).id} />;
}
// generated:end
