// Generated by `flare gen resource File`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=e4892f5168e5
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import fileResource from "@/resources/file.resource";

export default async function EditFilePage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={fileResource} id={(await params).id} />;
}
// generated:end
