// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1168c1c950ec
import { createResourceHandlers } from "@flare/core/server";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { authorize } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import planResource from "@/resources/plan.resource";

const handlers = createResourceHandlers({
  resource: planResource,
  table: plans,
  getDb,
  authorize,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
