// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3cc98088f3bd
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import purchaseResource from "@/resources/purchase.resource";

export const metadata = { title: purchaseResource.pluralLabel };

export default async function PurchaseListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={purchaseResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: purchaseResource.pluralLabel }]}
      />
      <ResourceStats resource={purchaseResource} />
      <ResourceChart resource={purchaseResource} />
      <ResourceTable resource={purchaseResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
