// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=7c2f26e22f4a
import { createResourceHandlers } from "@flaredev/core/server";
import { prismaRows } from "@flaredev/core/server";
import { prisma } from "@/lib/db";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import categoryResource from "@/resources/category.resource";

const handlers = createResourceHandlers({
  resource: categoryResource,
  rows: prismaRows(prisma.category, prisma),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
