// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=e2159342251e
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import securityEventResource from "@/resources/security-event.resource";

export default async function SecurityEventListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">{securityEventResource.pluralLabel}</h1>
      <ResourceTable resource={securityEventResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
