// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=cf1acec422e1
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import vendorResource from "@/resources/vendor.resource";

export default async function VendorListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">{vendorResource.pluralLabel}</h1>
      <ResourceTable resource={vendorResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
