// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=bfb5e37b336b
import { FormSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton actions={0} />
      <FormSkeleton fields={5} />
    </>
  );
}
// generated:end
