// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=9ec1e655e69d
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import orderResource from "@/resources/order.resource";

export default async function EditOrderPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={orderResource} id={(await params).id} />;
}
// generated:end
