// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1b4c141c812b
import { DetailSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton />
      <DetailSkeleton rows={6} />
    </>
  );
}
// generated:end
