// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=7dfd51f61be7
import { RecordDetail } from "@/components/dashboard/record-detail";
import dealResource from "@/resources/deal.resource";

export default async function DealDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={dealResource} id={(await params).id} />;
}
// generated:end
