// Generated by `flare gen resource Contact`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=40b5ad3aa5d7
import { createResourceHandlers, drizzleRows } from "@/lib/resource";
import { getDb } from "@/db";
import { contacts } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import contactResource from "@/resources/contact.resource";

const handlers = createResourceHandlers({
  resource: contactResource,
  rows: drizzleRows(contacts, getDb),
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
