import { chromium } from "playwright-core";
const base = "http://localhost:3300";
const browser = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } });
page.setDefaultNavigationTimeout(180000);
page.on("console", (m) => { const t = m.text(); if (t.includes("[form]")) console.log("  ", t); });
const go = (p) => page.goto(`${base}${p}`, { waitUntil: "domcontentloaded" });
await go("/sign-up");
await page.waitForSelector("#password", { timeout: 240000 });
await page.waitForFunction(() => { const el = document.querySelector("#password"); return el && Object.keys(el).some((k) => k.startsWith("__react")); }, null, { timeout: 240000 });
await page.fill("#name", "Create Test");
await page.fill("#email", `ct${Date.now()}@example.com`);
await page.fill("#password", "trombone harbour cedar 41");
await page.click('button[type="submit"]');
await page.waitForTimeout(10000);
await go("/dashboard/products");
await page.waitForSelector("tr", { timeout: 120000 });
await page.waitForTimeout(5000);
await page.getByRole("button", { name: /new product/i }).click();
await page.waitForTimeout(3000);
const sheet = page.getByRole("dialog");

// Try Next with a required field empty — it should stop and say so.
await page.getByRole("button", { name: /^Next$/ }).click();
await page.waitForTimeout(1200);
const blocked = (await page.getByRole("dialog").innerText()).replace(/\s+/g, " ");
console.log("BLOCKED ON STEP 1:", blocked.includes("Step 1 of 2") ? "stayed" : "advanced", "|", blocked.slice(blocked.indexOf("Name"), blocked.indexOf("Name") + 90));

await page.fill("#field-name", "Walnut monitor stand");
await page.getByRole("dialog").getByRole("button", { name: /generate/i }).first().click();
await page.waitForTimeout(500);
await page.locator('button:has-text("Choose kind")').click();
await page.waitForTimeout(800);
await page.getByRole("option", { name: /^Stock$/ }).click();
await page.fill("#field-price", "12500");
await page.fill("#field-stock", "7");
await page.getByRole("button", { name: /^Next$/ }).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: process.env.SHOT });
console.log("dialogs:", await page.getByRole("dialog").count());
console.log("BODY:", (await page.locator("body").innerText()).replace(/\s+/g, " ").slice(0, 200));
const probe = await page.request.get(`${base}/api/products?q=Walnut&perPage=2`);
console.log("WALNUT ROWS:", JSON.stringify((await probe.json()).data ?? []).slice(0, 220));
console.log("STEP 2:", (await page.getByRole("dialog").innerText()).replace(/\s+/g, " ").slice(0, 230));
await page.getByRole("button", { name: /create product/i }).click();
await page.waitForTimeout(7000);
const after = (await page.locator("body").innerText()).replace(/\s+/g, " ");
console.log("CREATED:", after.includes("Walnut monitor stand") ? "row is in the list" : after.slice(0, 160));
const api = await page.request.get(`${base}/api/products?perPage=1&sort=-createdAt`);
console.log("RECORD:", JSON.stringify((await api.json()).data?.[0] ?? {}).slice(0, 190));
await browser.close();
