// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3b9b82101aa6
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import productResource from "@/resources/product.resource";

export default function NewProductPage() {
  return <ResourceFormPage resource={productResource} />;
}
// generated:end
