// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=b31175dca0ee
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { orders } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import orderResource from "@/resources/order.resource";

const handlers = createResourceHandlers({
  resource: orderResource,
  table: orders,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
