// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=6c1a84490b2e
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import customerResource from "@/resources/customer.resource";

export const metadata = { title: customerResource.pluralLabel };

export default async function CustomerListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={customerResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: customerResource.pluralLabel }]}
      />
      <ResourceStats resource={customerResource} />
      <ResourceTable resource={customerResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
