// Generated by `flare gen resource Plan`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=bace7a43b5e4
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import planResource from "@/resources/plan.resource";

export default async function EditPlanPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={planResource} id={(await params).id} />;
}
// generated:end
