// Generated by `flare gen resource Product`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=dad50d685637
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import productResource from "@/resources/product.resource";

export const metadata = { title: productResource.pluralLabel };

export default async function ProductListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={productResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: productResource.pluralLabel }]}
      />
      <ResourceStats resource={productResource} />
      <ResourceChart resource={productResource} />
      <ResourceTable resource={productResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
