// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=15d196e27d42
import { createResourceClient } from "@flaredev/core/client";
import type categoryResource from "./category.resource";

export const categoryClient = createResourceClient<typeof categoryResource>("/api/categories");

export type Category = typeof categoryResource.$types.record;
export type CategoryCreate = typeof categoryResource.$types.create;
export type CategoryUpdate = typeof categoryResource.$types.update;
// generated:end
