// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a68da8161580
import { createValidators } from "@flaredev/core";
import customerResource from "./customer.resource";

export const customerValidators = createValidators(customerResource);
// generated:end
