// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f7e6c1339e72
import { createResourceClient } from "@flaredev/core/client";
import type orderResource from "./order.resource";

export const orderClient = createResourceClient<typeof orderResource>("/api/orders");

export type Order = typeof orderResource.$types.record;
export type OrderCreate = typeof orderResource.$types.create;
export type OrderUpdate = typeof orderResource.$types.update;
// generated:end
