// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d37821de4dfd
import { createValidators } from "@flaredev/core";
import orderItemResource from "./order-item.resource";

export const orderItemValidators = createValidators(orderItemResource);
// generated:end
