// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=2d152bdff1f2
import { createResourceClient } from "@flaredev/core/client";
import type orderItemResource from "./order-item.resource";

export const orderItemClient = createResourceClient<typeof orderItemResource>("/api/order-items");

export type OrderItem = typeof orderItemResource.$types.record;
export type OrderItemCreate = typeof orderItemResource.$types.create;
export type OrderItemUpdate = typeof orderItemResource.$types.update;
// generated:end
