// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=dc9c63574aff
import { ResourceFormPage } from "@/components/admin/resource-form-page";
import securityEventResource from "@/resources/security-event.resource";

export default async function EditSecurityEventPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={securityEventResource} id={(await params).id} />;
}
// generated:end
