// Generated by `flare gen resource Vendor`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1939c6bb8295
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import vendorResource from "@/resources/vendor.resource";

export default function NewVendorPage() {
  return <ResourceFormPage resource={vendorResource} />;
}
// generated:end
