// Generated by `flare gen resource Order`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f6256edcbaa1
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { orders } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import orderResource from "@/resources/order.resource";

const handlers = createResourceHandlers({
  resource: orderResource,
  table: orders,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
