// Generated by `flare gen security`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3f1ed0349451
"use server";

import { revalidatePath } from "next/cache";
import { can } from "@flaredev/core";
import { isIp } from "@flaredev/core/security";
import { dashboardSession, policyFor } from "@/lib/dashboard";
import { logSecurityEvent, security } from "@/lib/security";

/** On failure the submitted values come back, so the form (which React resets) keeps them. */
export type BanResult = { ok: true } | { ok: false; error: string; ip?: string; reason?: string };

const DURATIONS: Record<string, number | null> = { "1h": 3600, "24h": 86_400, "7d": 604_800, permanent: null };

async function adminOnly(): Promise<{ email: string } | { error: string }> {
  const { session, role } = await dashboardSession();
  if (!session) return { error: "Sign in required." };
  if (!can(policyFor("SecurityEvent"), role, "create")) return { error: "Only admins can ban or unban." };
  return { email: session.user.email };
}

/** Ban an IP at every layer this app has (Worker, and the zone when configured). */
export async function banAction(_previous: BanResult | null, form: FormData): Promise<BanResult> {
  const admin = await adminOnly();
  if ("error" in admin) return { ok: false, error: admin.error };
  const ip = String(form.get("ip") ?? "").trim();
  const reason = String(form.get("reason") ?? "").trim() || "Banned manually";
  const duration = String(form.get("duration") ?? "24h");
  if (!isIp(ip)) return { ok: false, error: `"${ip}" isn't an IP address.`, ip, reason };
  if (!(duration in DURATIONS)) return { ok: false, error: "Choose how long to ban for.", ip, reason };

  try {
    await security().ban(ip, `${reason} (by ${admin.email})`, DURATIONS[duration]!, null);
  } catch (error) {
    return { ok: false, error: `The ban didn't reach every layer: ${error instanceof Error ? error.message : String(error)}`, ip, reason };
  }
  await logSecurityEvent({ kind: "manual-ban", severity: "medium", ip, path: "/dashboard/security", userAgent: null, count: 0, banned: true, detail: `${reason} (by ${admin.email})` });
  revalidatePath("/dashboard/security");
  return { ok: true };
}

export async function unbanAction(ip: string): Promise<BanResult> {
  const admin = await adminOnly();
  if ("error" in admin) return { ok: false, error: admin.error };
  if (!isIp(ip)) return { ok: false, error: `"${ip}" isn't an IP address.` };
  try {
    await security().unban(ip);
  } catch (error) {
    return { ok: false, error: `The unban didn't reach every layer: ${error instanceof Error ? error.message : String(error)}` };
  }
  await logSecurityEvent({ kind: "manual-unban", severity: "low", ip, path: "/dashboard/security", userAgent: null, count: 0, banned: false, detail: `by ${admin.email}` });
  revalidatePath("/dashboard/security");
  return { ok: true };
}
// generated:end
