// Generated by `flare gen security`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c9521331b44e
import Link from "next/link";
import { can } from "@flaredev/core";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { dashboardStore, policyFor, requireDashboard } from "@/lib/dashboard";
import { security, zoneClient } from "@/lib/security";
import { BanForm, UnbanButton } from "./ban-controls";

const TONE = { high: "danger", medium: "warning", low: "secondary" } as const;
const when = (value: string | number | Date | null) =>
  value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Until unbanned";

export default async function SecurityPage() {
  const { role } = await requireDashboard("/dashboard/security");
  if (!can(policyFor("SecurityEvent"), role, "read")) {
    return (
      <Alert>
        <AlertDescription>Your role can't view security activity.</AlertDescription>
      </Alert>
    );
  }
  const canBan = can(policyFor("SecurityEvent"), role, "create");
  const zone = zoneClient();

  const [bans, events, edge] = await Promise.all([
    security().bans(),
    dashboardStore("SecurityEvent").list(new URLSearchParams({ sort: "-createdAt", perPage: "20" })),
    zone
      ? Promise.all([zone.bans(), zone.firewallEvents(new Date(Date.now() - 24 * 3600 * 1000))]).then(
          ([zoneBans, firewall]) => ({ ok: true as const, zoneBans, firewall }),
          (error: unknown) => ({ ok: false as const, error: error instanceof Error ? error.message : String(error) }),
        )
      : Promise.resolve(null),
  ]);
  const recent = events.ok ? events.data.data : [];
  const zoneIps = new Set(edge?.ok ? edge.zoneBans.map((ban) => ban.ip) : []);
  const blockedTotal = bans.reduce((sum, ban) => sum + ban.blocked, 0);

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold">Security</h1>
          <p className="text-sm text-muted-foreground">
            Worker layer on{zone ? ", zone rules on" : "; zone rules off (set FLARE_SECURITY_ZONE_ID and FLARE_SECURITY_API_TOKEN)"}.
          </p>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader>
            <CardDescription>Active bans</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">{bans.length}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Requests blocked by bans</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">{blockedTotal}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Zone firewall events, 24h</CardDescription>
            <CardTitle className="text-3xl font-bold tabular-nums">
              {edge?.ok ? edge.firewall.reduce((sum, row) => sum + row.count, 0) : "—"}
            </CardTitle>
          </CardHeader>
        </Card>
      </div>

      {edge && !edge.ok && (
        <Alert>
          <AlertDescription>The zone layer couldn't be read: {edge.error}</AlertDescription>
        </Alert>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Banned IPs</CardTitle>
          <CardDescription>Refused before the app runs{zone ? ", and blocked at the zone edge" : ""}.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          {bans.length === 0 ? (
            <Empty className="border border-dashed">
              <EmptyHeader>
                <EmptyTitle>No active bans</EmptyTitle>
                <EmptyDescription>IPs that trip a detector with a ban, or that you ban here, appear in this list.</EmptyDescription>
              </EmptyHeader>
            </Empty>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>IP</TableHead>
                  <TableHead>Reason</TableHead>
                  <TableHead>Blocked</TableHead>
                  <TableHead>Until</TableHead>
                  {canBan && <TableHead className="w-0" />}
                </TableRow>
              </TableHeader>
              <TableBody>
                {bans.map((ban) => (
                  <TableRow key={ban.ip}>
                    <TableCell className="font-medium tabular-nums">
                      <span className="flex items-center gap-2">
                        {ban.ip}
                        {zoneIps.has(ban.ip) && <Badge variant="secondary">zone</Badge>}
                      </span>
                    </TableCell>
                    <TableCell className="max-w-80 truncate text-muted-foreground">{ban.reason}</TableCell>
                    <TableCell className="tabular-nums">{ban.blocked}</TableCell>
                    <TableCell className="text-muted-foreground">{when(ban.until)}</TableCell>
                    {canBan && (
                      <TableCell>
                        <UnbanButton ip={ban.ip} />
                      </TableCell>
                    )}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
          {canBan && (
            <>
              <Separator />
              <BanForm />
            </>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent events</CardTitle>
          <CardDescription>
            Detectors that tripped, and manual bans. <Link href="/dashboard/security-events" className="underline underline-offset-4">All events</Link>
          </CardDescription>
        </CardHeader>
        <CardContent>
          {recent.length === 0 ? (
            <p className="text-sm text-muted-foreground">Nothing yet.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>When</TableHead>
                  <TableHead>Event</TableHead>
                  <TableHead>IP</TableHead>
                  <TableHead>Count</TableHead>
                  <TableHead>Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {recent.map((event) => (
                  <TableRow key={String(event.id)}>
                    <TableCell className="text-muted-foreground">{when(event.createdAt as Date)}</TableCell>
                    <TableCell>
                      <span className="flex items-center gap-2">
                        <Badge variant={TONE[event.severity as keyof typeof TONE] ?? "secondary"}>{String(event.severity)}</Badge>
                        {String(event.kind)}
                      </span>
                    </TableCell>
                    <TableCell className="tabular-nums">{String(event.ip)}</TableCell>
                    <TableCell className="tabular-nums">{Number(event.count) || "—"}</TableCell>
                    <TableCell className="text-muted-foreground">{event.banned ? "Banned" : "Logged"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {edge?.ok && (
        <Card>
          <CardHeader>
            <CardTitle>Zone firewall, last 24 hours</CardTitle>
            <CardDescription>What Cloudflare's edge did before requests reached the Worker.</CardDescription>
          </CardHeader>
          <CardContent>
            {edge.firewall.length === 0 ? (
              <p className="text-sm text-muted-foreground">No firewall events.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Action</TableHead>
                    <TableHead>Source</TableHead>
                    <TableHead>Rule</TableHead>
                    <TableHead>Events</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {edge.firewall.map((row, index) => (
                    <TableRow key={index}>
                      <TableCell>{row.action}</TableCell>
                      <TableCell className="text-muted-foreground">{row.source}</TableCell>
                      <TableCell className="text-muted-foreground">{row.description ?? "—"}</TableCell>
                      <TableCell className="tabular-nums">{row.count}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
// generated:end
