// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=ff045e099948
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import categoryResource from "@/resources/category.resource";

export default async function EditCategoryPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={categoryResource} id={(await params).id} />;
}
// generated:end
