// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=5b4ee79e2bbe
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import customerResource from "@/resources/customer.resource";

export default async function CustomerListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">{customerResource.pluralLabel}</h1>
      <ResourceTable resource={customerResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
