// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a3c02e0739ea
import { createResourceHandlers } from "@flare/core/server";
import { getDb } from "@/db";
import { companies } from "@/db/schema";
import { authorize } from "@/lib/api";
import companyResource from "@/resources/company.resource";

const handlers = createResourceHandlers({
  resource: companyResource,
  table: companies,
  getDb,
  authorize,
});

export const GET = handlers.item.GET;
export const PATCH = handlers.item.PATCH;
export const PUT = handlers.item.PUT;
export const DELETE = handlers.item.DELETE;
// generated:end
