// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1e7fdcb7e639
import Link from "next/link";
import { PlusIcon } from "lucide-react";
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import { Button } from "@/components/ui/button";
import companyResource from "@/resources/company.resource";

export default async function CompanyListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between gap-4">
        <h1 className="text-2xl font-semibold">{companyResource.pluralLabel}</h1>
        <Button asChild>
          <Link href={`/admin/${companyResource.slug}/new`}>
            <PlusIcon data-icon="inline-start" />
            New {companyResource.label.toLowerCase()}
          </Link>
        </Button>
      </div>
      <ResourceTable resource={companyResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
