// Generated by `flare gen resource Company`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=cdcff5649ae6
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import companyResource from "@/resources/company.resource";

export default async function CompanyListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">{companyResource.pluralLabel}</h1>
      <ResourceTable resource={companyResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
