// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=239b41f4dbf5
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import folderResource from "@/resources/folder.resource";

export default function NewFolderPage() {
  return <ResourceFormPage resource={folderResource} />;
}
// generated:end
