// Generated by `flare gen resource Purchase`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c3f1cad8ad3c
import { RecordDetail } from "@/components/dashboard/record-detail";
import purchaseResource from "@/resources/purchase.resource";

export default async function PurchaseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={purchaseResource} id={(await params).id} />;
}
// generated:end
