// Generated by `flare gen resource Folder`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1d92bdaa5f0c
import { createResourceHandlers } from "@flaredev/core/server";
import { getDb } from "@/db";
import { folders } from "@/db/schema";
import { authorize, currentUser } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import folderResource from "@/resources/folder.resource";

const handlers = createResourceHandlers({
  resource: folderResource,
  table: folders,
  getDb,
  authorize,
  currentUser,
  onChange: revalidateResource,
});

export const GET = handlers.collection.GET;
export const POST = handlers.collection.POST;
// generated:end
