// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=318d2422dfc6
import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { isLiveSubscription } from "@flaredev/core";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { getSession } from "@/lib/session";
import { appOrigin, billingPortalConfiguration, createStripe, getOrCreateCustomer } from "@/lib/stripe";

/**
 * POST {} opens the portal (payment methods, invoices, cancel). POST { planSlug }
 * opens its plan-change confirmation for that plan: Stripe shows the prorated
 * amount and applies the change to the existing subscription, so switching plans
 * never starts a second one.
 */
export async function POST(request: NextRequest) {
  const raw = await request.text();
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Sign in to manage billing." }, { status: 401 });

  let planSlug = "";
  try {
    planSlug = raw ? String((JSON.parse(raw) as { planSlug?: unknown }).planSlug ?? "") : "";
  } catch {
    return NextResponse.json({ error: "Send JSON like {\"planSlug\": \"pro\"}, or no body." }, { status: 400 });
  }

  const customer = await getOrCreateCustomer(session.user);
  const stripe = createStripe();
  const returnUrl = `${appOrigin(request)}/dashboard/billing`;

  const configuration = await billingPortalConfiguration(stripe);

  if (!planSlug) {
    const portal = await stripe.billingPortal.sessions.create({ customer: customer.stripeCustomerId, return_url: returnUrl, configuration });
    return NextResponse.json({ url: portal.url });
  }

  const plan = await getDb().select().from(plans).where(eq(plans.slug, planSlug)).get();
  if (!plan || plan.active === false || !plan.interval) return NextResponse.json({ error: "That plan isn't available." }, { status: 404 });
  if (!customer.stripeSubscriptionId || !isLiveSubscription(customer.subscriptionStatus)) {
    return NextResponse.json({ error: "You don't have a subscription to change yet. Subscribe first." }, { status: 409 });
  }
  const subscription = await stripe.subscriptions.retrieve(customer.stripeSubscriptionId);
  const item = subscription.items.data[0];
  if (!item) return NextResponse.json({ error: "The subscription has no items to change." }, { status: 409 });

  const portal = await stripe.billingPortal.sessions.create({
    customer: customer.stripeCustomerId,
    return_url: returnUrl,
    configuration,
    flow_data: {
      type: "subscription_update_confirm",
      subscription_update_confirm: {
        subscription: subscription.id,
        items: [{ id: item.id, price: plan.stripePriceId, quantity: 1 }],
      },
      after_completion: { type: "redirect", redirect: { return_url: `${returnUrl}?changed=1` } },
    },
  });
  return NextResponse.json({ url: portal.url });
}
// generated:end
