// Generated by `flare gen billing`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=efacabe31b51
import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { isLiveSubscription, randomLetters } from "@flare/core";
import { getDb } from "@/db";
import { plans } from "@/db/schema";
import { getSession } from "@/lib/session";
import { appOrigin, createStripe, getOrCreateCustomer } from "@/lib/stripe";

/**
 * POST { planSlug }. The plan decides the mode: a recurring price starts a
 * subscription, a one-time price a payment. Prices only ever come from the Plan
 * table, so a client can't pay for an arbitrary price. A customer who already has
 * a subscription changes plans through the portal instead of buying a second one.
 */
export async function POST(request: NextRequest) {
  const raw = await request.text();
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Sign in to check out." }, { status: 401 });

  let planSlug = "";
  try {
    planSlug = String((JSON.parse(raw) as { planSlug?: unknown }).planSlug ?? "");
  } catch {
    return NextResponse.json({ error: "Send JSON like {\"planSlug\": \"pro\"}." }, { status: 400 });
  }
  const plan = planSlug ? await getDb().select().from(plans).where(eq(plans.slug, planSlug)).get() : undefined;
  if (!plan || plan.active === false) return NextResponse.json({ error: "That plan isn't available." }, { status: 404 });

  const mode = plan.interval ? "subscription" : "payment";
  const customer = await getOrCreateCustomer(session.user);
  if (mode === "subscription" && isLiveSubscription(customer.subscriptionStatus)) {
    return NextResponse.json({ error: "You already have a subscription. Change plans from the billing page." }, { status: 409 });
  }

  const base = appOrigin(request);
  const checkout = await createStripe().checkout.sessions.create({
    mode,
    line_items: [{ price: plan.stripePriceId, quantity: 1 }],
    customer: customer.stripeCustomerId,
    client_reference_id: customer.id,
    integration_identifier: `flare-billing-${randomLetters()}`,
    success_url: `${base}/dashboard/billing?checkout=success&session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `${base}/dashboard/billing?checkout=cancelled`,
  });
  if (!checkout.url) return NextResponse.json({ error: "Stripe did not return a checkout URL." }, { status: 502 });
  return NextResponse.json({ url: checkout.url });
}
// generated:end
