// Generated by `flare gen resource Category`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=0178a8586287
import { RecordDetail } from "@/components/dashboard/record-detail";
import categoryResource from "@/resources/category.resource";

export default async function CategoryDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={categoryResource} id={(await params).id} />;
}
// generated:end
