// Generated by `flare gen resource OrderItem`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=265bab56064b
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import orderItemResource from "@/resources/order-item.resource";

export default async function EditOrderItemPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={orderItemResource} id={(await params).id} />;
}
// generated:end
