// Generated by `flare gen resource Deal`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=5db719a02430
import Link from "next/link";
import { PlusIcon } from "lucide-react";
import { ResourceTable } from "@/components/admin/resource-table";
import type { SearchParams } from "@/components/admin/query";
import { Button } from "@/components/ui/button";
import dealResource from "@/resources/deal.resource";

export default async function DealListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between gap-4">
        <h1 className="text-2xl font-semibold">{dealResource.pluralLabel}</h1>
        <Button asChild>
          <Link href={`/admin/${dealResource.slug}/new`}>
            <PlusIcon data-icon="inline-start" />
            New {dealResource.label.toLowerCase()}
          </Link>
        </Button>
      </div>
      <ResourceTable resource={dealResource} searchParams={await searchParams} />
    </div>
  );
}
// generated:end
