// Generated by `flare gen resource Customer`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=29f57c8e7fb3
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import customerResource from "@/resources/customer.resource";

export default function NewCustomerPage() {
  return <ResourceFormPage resource={customerResource} />;
}
// generated:end
